'use strict';
// Murch dashboard data - update THIS file for daily changes
const assetVersion = '20260627-whatsapp-field';
const assetBase = 'https://claped71.github.io/murch-dashboard/';
function asset(path) { return assetBase + path + '?v=' + assetVersion; }
function assetFallback(path) { return assetBase + path; }
window.MURCH_DATA = {
    scope: [
      { title: 'EPC Management', metric: 'Turnkey', note: 'Project management, safety, QC, contractor deliverables, owner reporting, permitting support, and trade coordination through completion.' },
      { title: 'Civil and Environmental', metric: 'F starts Jul 1', note: 'Rosario Week 24 controls baseline progress; June 26 field note adds Area E expected complete Jun 30, Area F start Jul 1, and Area G basins 66/70 grading/piping sequence.' },
      { title: 'Mechanical BOS', metric: '31,352 piles', note: 'Pile driving, D&F pre-drilling where required, GameChange SAT tracker assembly, purlin install, and module placement.' },
      { title: 'Electrical BOS', metric: 'ITS plowing on site', note: 'MV collection, HDD, plowing, grounding, DC string and combiner wiring, LV/AC works, inverter installation, SCADA, and testing. Joshua Spalding reported the ITS plowing machine arrived on June 19.' },
      { title: 'Procurement', metric: '171,470 modules', note: 'Panels, racking, purlins, actuators, controllers, cables, inverter stations, combiner boxes, and SET equipment.' },
      { title: 'Commissioning', metric: 'PIS Oct 16', note: 'Cold commissioning, energization, tracker testing, inverter start-up, PR test path, punch list, COD, and substantial completion.' }
    ],
    photos: [
      { src: asset('assets/recent/recent-26.jpg'), fallbackSrc: assetFallback('assets/recent/recent-26.jpg'), date: 'July 1, 2026', title: 'Control-building access platform fabrication', note: 'Factory photo of yellow access platform/stair components for the control-building package; FAT status was reported as passed in the July 1 field chat.' },
      { src: asset('assets/recent/recent-27.jpg'), fallbackSrc: assetFallback('assets/recent/recent-27.jpg'), date: 'July 1, 2026', title: 'Control-building platform and handrail detail', note: 'Additional factory view of control-building access-platform details, supporting the July 7 control-building delivery gate.' },
      { src: asset('assets/recent/recent-21.jpg'), fallbackSrc: assetFallback('assets/recent/recent-21.jpg'), date: 'June 25, 2026', title: 'Golden Row installation', note: 'Golden Row tracker/racking installation shared by Audelio Zuniga, documenting the first representative mechanical completion sequence ahead of module release.' },
      { src: asset('assets/recent/recent-23.jpg'), fallbackSrc: assetFallback('assets/recent/recent-23.jpg'), date: 'June 25, 2026', title: 'ITS MV plowing workfront', note: 'MV cable/plowing workfront activity, supporting the ITS start-up sequence that must now convert into measured feet and completed segments.' },
      { src: asset('assets/recent/recent-22.jpg'), fallbackSrc: assetFallback('assets/recent/recent-22.jpg'), date: 'June 25, 2026', title: 'SET control-building reference photo', note: 'Control-building visual shared by Axel Cano. The June 26 SET workbook still carries the control building as in fabrication with a July 7 committed date, so delivery remains a tracked gate.' },
      { src: asset('assets/recent/recent-24.jpg'), fallbackSrc: assetFallback('assets/recent/recent-24.jpg'), date: 'June 24, 2026', title: 'Civil/fence workfront conditions', note: 'Field view of civil and fencing workfront conditions supporting Area E/F/G release sequencing.' },
      { src: asset('assets/recent/recent-25.jpg'), fallbackSrc: assetFallback('assets/recent/recent-25.jpg'), date: 'June 25, 2026', title: 'Purlin slot detail for module-fit control', note: 'Golden Row detail photo used as quality evidence: module spacing must be measured during tightening because slot tolerance can slow module installation.' },
      { src: asset('assets/recent/recent-20.jpg'), fallbackSrc: assetFallback('assets/recent/recent-20.jpg'), date: 'June 25, 2026', title: 'Golden Row installation', note: 'Field crew installing the Golden Row tracker/racking assembly, documenting the first representative mechanical installation sequence.' },
      { src: asset('assets/recent/recent-14.jpg'), fallbackSrc: assetFallback('assets/recent/recent-14.jpg'), date: 'June 19, 2026', title: 'Racking workfront beside stabilized access', note: 'Installed pile and racking lines beside the project access road, documenting active mechanical workfront conditions.' },
      { src: asset('assets/recent/recent-13.jpg'), fallbackSrc: assetFallback('assets/recent/recent-13.jpg'), date: 'June 19, 2026', title: 'Tracker and racking installation', note: 'Wide field view of active tracker and racking installation, showing the scale of the released mechanical workfront.' },
      { src: asset('assets/recent/recent-15.jpg'), fallbackSrc: assetFallback('assets/recent/recent-15.jpg'), date: 'June 19, 2026', title: 'ITS MV boring operation', note: 'Excavator and crew supporting the ITS medium-voltage boring scope at the wooded crossing workfront.' },
      { src: asset('assets/recent/recent-16.jpg'), fallbackSrc: assetFallback('assets/recent/recent-16.jpg'), date: 'June 19, 2026', title: 'MV conduit handling and bore preparation', note: 'ITS crew handling conduit and preparing the bore workfront for the underground medium-voltage crossing.' },
      { src: asset('assets/recent/recent-17.jpg'), fallbackSrc: assetFallback('assets/recent/recent-17.jpg'), date: 'June 19, 2026', title: 'MV boring materials staged in Area F', note: 'Conduit and boring materials staged at the Area F crossing, showing the physical preparation for the ITS installation sequence.' },
      { src: asset('assets/recent/recent-18.jpg'), fallbackSrc: assetFallback('assets/recent/recent-18.jpg'), date: 'June 19, 2026', title: 'Wooded crossing workfront preparation', note: 'Compact equipment clearing and preparing access at the wooded MV crossing before boring and conduit installation.' },
      { src: asset('assets/recent/recent-19.jpg'), fallbackSrc: assetFallback('assets/recent/recent-19.jpg'), date: 'June 19, 2026', title: 'Substation foundation formwork', note: 'Substation foundation and containment formwork under construction, documenting current SET civil progress.' },
      { src: asset('assets/recent/recent-1.jpg'), fallbackSrc: assetFallback('assets/recent/recent-1.jpg'), date: 'June 19, 2026', title: 'ITS plowing machine arrival', note: 'Joshua Spalding reported that the ITS plowing machine arrived on site for the MW cable scope; this photo shows the equipment staged and ready for electrical mobilization.' },
      { src: asset('assets/recent/recent-4.jpg'), fallbackSrc: assetFallback('assets/recent/recent-4.jpg'), date: 'June 17, 2026', title: 'Tracker workfront conditions', note: 'June 17 site photo showing muddy tracker rows, standing water, and access conditions affecting mechanical and follow-on workfront continuity.' },
      { src: asset('assets/recent/recent-7.jpg'), fallbackSrc: assetFallback('assets/recent/recent-7.jpg'), date: 'June 11, 2026', title: 'Environmental controls and field support', note: 'Civil and environmental view showing stabilized access, sediment-control wattles, drainage protection, and support facilities.' },
      { src: asset('assets/recent/recent-8.jpg'), fallbackSrc: assetFallback('assets/recent/recent-8.jpg'), date: 'June 3, 2026', title: 'Aerial civil and laydown context', note: 'Drone view showing the broader civil layout, access roads, laydown area, and surrounding project workfronts.' },
      { src: asset('assets/recent/recent-11.jpg'), fallbackSrc: assetFallback('assets/recent/recent-11.jpg'), date: 'May 26, 2026', title: 'Basin and road stabilization', note: 'Representative civil/environmental photo showing stabilized basin slopes and access-road construction.' }
    ],
    weeklyPlan: [
      { area: '<u>Pile production recovery — Zones B / F / D-G</u><span style="background:#b53030;color:#fff;padding:1px 6px;border-radius:3px;font-size:10px;font-weight:700;margin-left:6px">CRITICAL</span>', target: 'Recover ramming output: 14,284 piles remain with only ~15 working days to the Jul 28 pile-complete gate. Last measured days (270, 213, 138) show a worsening trend.', minimum: '>= 715 piles/day now required; latest field output was 138-270/day — below 40% of requirement', gate: 'Kalamazoo pre-drill decision for Area F hard soil (~3,000 holes discussed), rig repairs (2 damaged; only 5 operating Jul 3 due to operator rest), and daily pile-stock re-feed inside the receiving cap.', owners: 'LATNOVVA / United | Audelio Zuniga | Manuel Ramirez | Joshua Spalding' },
      { area: '<u>GameChange purlin + post deliveries</u><span style="background:#b53030;color:#fff;padding:1px 6px;border-radius:3px;font-size:10px;font-weight:700;margin-left:6px">CRITICAL</span>', target: 'Close POD/site-receipt confirmation of the Jul 2-3 loads (15 named containers) and keep the Jul 16 final tracker-purlin delivery gate protected.', minimum: 'Jul 6 piles-only where possible; from Jul 7 receive up to 14 pile loads/day plus 8 racking loads/day if appointments and offloading resources hold.', gate: 'Purlin receipts remain the project critical-path gate: any slip moves tracker completion, module start, and Mechanical Completion day-for-day.', owners: 'GameChange (Shreeya Devkota) | Manuel Ramirez | Briana Figueroa' },
      { area: '<u>Module installation ramp — Area A</u><span style="background:#b53030;color:#fff;padding:1px 6px;border-radius:3px;font-size:10px;font-weight:700;margin-left:6px">CRITICAL</span>', target: 'Module erection has started (234 on Jul 3). Ramp Workforce from 12 to the full 22-person crew and place 8,000-10,000 cumulative modules this week.', minimum: 'Reach >= 2,000 modules/day by Friday Jul 10; the acceleration plan requires 5,531/day full-field from mid-July', gate: 'QA-released purlin-complete rows + measured module-spacing QC control (Golden Row slot-tolerance finding) + crew ramp on schedule.', owners: 'Workforce | Audelio Zuniga | Daniel Morilla (QA/QC) | Manuel Ramirez' },
      { area: 'Tracker assembly and purlin row completion', target: 'Sustain the first above-target result (Jul 1: 51 units): close Area A (98 rows remaining), open Area C, and keep Steps 1-6 rolling into C/E.', minimum: '>= 48 tracker units/day sustained all week and ramp toward 40 completed rows/day', gate: 'Complete purlin kits allocated by block and same-week QA turnover of finished rows.', owners: 'ECCS | Audelio Zuniga | Manuel Ramirez' },
      { area: 'Civil Area F/G release and internal roads', target: 'Area F grading at full production, Area G basins 66/70 piping and structure, and push internal roads beyond 35%.', minimum: 'Daily confirmed grading production in Area F; roads remain the controlling logistics constraint', gate: 'Civil access, fencing gates, and drainage release ahead of the mechanical fronts.', owners: 'Lounsbury / Hurricane / Topland | Rosario Ruiz | Audelio Zuniga' },
      { area: 'Electrical MV plowing and HDD closeout', target: 'Sustain plowing production (30 of 46 segments remaining) and continue closing the remaining 10 bores.', minimum: '>= 1 plow segment/day and >= 1 completed bore/day with measured footage reporting', gate: 'Crossing approvals, access continuity, and equipment availability.', owners: 'ITS | Angel Urbina | Joshua Spalding' },
      { area: 'SET control building and inverter foundations', target: 'Receive the control building on the Jul 7 committed date (FAT passed Jul 1), hold the Jul 10 required-on-site gate, and complete inverter pile foundations before the end-July arrival of the 23 inverter units.', minimum: '100% control-building foundation accepted; inverter foundations released ahead of first delivery', gate: 'Procurement acceleration on SET items still committed after the Jul 10 gate.', owners: 'AB Power / SET team | Axel Cano | Joshua Spalding | Karina Mucino' },
      { area: 'LV aerial-system readiness', target: 'Receive the first Chemik pre-tailored cable reels on Jul 7 and start East Carolina plus self-perform crews immediately behind released module blocks.', minimum: '>= 1 first-batch cable package received and >= 1 LV block package released by Jul 7', gate: 'Released module areas and East Carolina plus self-perform crew readiness.', owners: 'East Carolina / Greensol Self-Perform | Angel Urbina | Luis Romero | Karina Mucino' }
    ],
    civilKpis: [
      { title: 'Civil field progress', metric: 'Week 24', note: 'Rosario Ruiz Week 24 update dated June 19 and sent June 22 controls current civil percentages.' },
      { title: 'Area F/G release', metric: 'F Jul 1', note: 'June 26 civil field note: Area E expected complete June 30, Area F starts July 1, and Area G basins 66/70 grading continues with piping and structure planned Monday.' },
      { title: 'SET tracker', metric: '8.7% overall', note: 'The July 1 SET tracker reports 21 complete activities, 3 in progress, and 238 pending. Civil progress is 33.8%, structural progress is 1.9%, and electrical progress is 2.3%.' }
    ],
    civilActivities: [
      { activity: 'Earthworks cut / fill', company: 'Lounsbury', done: 61, remaining: 39, status: 'Active', note: 'Week 24 civil superintendent update. Started April 1; final date remains TBD pending release constraints.' },
      { activity: 'Perimeter fence', company: 'Hurricane', done: 76, remaining: 24, status: 'Active', note: 'Week 24 civil baseline remains 76%. June 26 field note says Areas A, B, C, E, EW and F are complete, with gates next and Zone G/substation still awaiting entry.' },
      { activity: 'Sediment basins / environmental controls', company: 'Lounsbury / ECS', done: 47, remaining: 53, status: 'At Risk', note: 'Week 24 civil superintendent update. Basin work started March 26 and is planned through July 15.' },
      { activity: 'Internal roads', company: 'Topland', done: 35, remaining: 65, status: 'Critical', note: 'Week 24 civil update shows roads in Areas A-B-C-E at 35% executed; roads continue to control logistics access.' },
      { activity: 'PS foundations', company: 'United', done: 38, remaining: 62, status: 'Critical', note: 'Week 24 civil update reports PS foundations at 38% executed, with work planned through August 10.' },
      { activity: 'Foundation SET', company: 'AB Power', done: 8.7, remaining: 91.3, status: 'Active', note: 'July 1 SET workbook shows overall substation progress at 8.7%; civil progress is 33.8%, structural progress is 1.9%, and electrical progress is 2.3%.' }
    ],
    contractors: [
      { name: 'LATNOVVA / assigned areas', scope: 19260, installed: 10655, remaining: 8605, done: 55.3, zones: 'Zones A, B, C, D, G, EW + shared Area E control', status: 'Watch', note: "Area-based control allocation only; it is not a new manpower or subcontractor headcount report." },
      { name: 'ECCS / Area E control', scope: 4434, installed: 4434, remaining: 0, done: 100, zones: 'Area E shared tracker workfront', status: 'On Track', note: "Area-based control allocation used only so dashboard totals reconcile with Audelio's June 30 official installed-production basis." },
      { name: 'United', scope: 7658, installed: 1223, remaining: 6435, done: 16.0, zones: 'Zone F', status: 'Active', note: 'United Zone F production is counted in the refreshed official workbook; continuity depends on hard-soil mitigation and confirmed pile deliveries.' },
      { name: 'Project Total', scope: 31352, installed: 17068, remaining: 14284, done: 54.4, zones: "All zones | Construction Manager report", status: 'Critical', note: "Audelio / Construction Manager July 1 Delivery/Mechanical workbook is the official installed-production basis." }
    ],
    zones: [
      { zone: 'Zone A', contractor: 'Latnovva', scope: 3834, installed: 3831, remaining: 3, done: 99.9, status: 'On Track', note: 'June 30 Const. Management workbook; nearly complete.' },
      { zone: 'Zone C', contractor: 'Latnovva', scope: 2946, installed: 2800, remaining: 146, done: 95.0, status: 'Active', note: 'June 30 Const. Management workbook.' },
      { zone: 'Zone E', contractor: 'ECCS / Latnovva', scope: 8456, installed: 8012, remaining: 444, done: 94.7, status: 'Active', note: 'June 30 Delivery / Mechanical roll-up.' },
      { zone: 'Zone EW', contractor: 'Latnovva', scope: 846, installed: 823, remaining: 23, done: 97.3, status: 'Active', note: 'June 30 Const. Management workbook; nearly complete.' },
      { zone: 'Zone B', contractor: 'Latnovva', scope: 2788, installed: 379, remaining: 2409, done: 13.6, status: 'Active', note: 'July 1 Delivery / Mechanical roll-up.' },
      { zone: 'Zone D', contractor: 'TBD / Latnovva', scope: 1468, installed: 0, remaining: 1468, done: 0, status: 'Material Hold', note: '2nd-50% work; no start before June 22 material arrivals.' },
      { zone: 'Zone F', contractor: 'United', scope: 7658, installed: 1223, remaining: 6435, done: 16.0, status: 'Active', note: 'July 1 Delivery / Mechanical roll-up shows Zone F production continuing, but hard soil remains the critical productivity risk.' },
      { zone: 'Zone G', contractor: 'Latnovva', scope: 3356, installed: 0, remaining: 3356, done: 0, status: 'Material Hold', note: 'Assigned to Latnovva. June 26 field note shows Lounsbury working basins 66 and 70 in Area G, with piping and structure planned next; mechanical release still needs confirmation.' }
    ],
    production: [
      { name: 'Project pile installation', remaining: '14,284 piles', target: '560 piles/day acceleration capacity', latest: 'Jun 30 official daily row: 234 piles', cumulative: '17,068 / 31,352 installed (54.4%)', status: 'Critical', note: 'Installed production follows Audelio / Construction Manager workbook. The latest official daily row remains below 50% of the acceleration target.' },
      { name: 'Pile delivery / site stock', remaining: '11,920 piles undelivered', target: 'Receipts must exceed 560 piles/day burn', latest: 'No delivery increase in July 1 workbook', cumulative: '19,432 delivered; 2,364 available above installed', status: 'Critical', note: 'Available stock equals delivered piles less officially installed piles. The current buffer covers about 4.2 production days at the acceleration-capacity assumption.' },
      { name: 'Drill and backfill', remaining: '0 pre-drills', target: 'Maintain no drill/backfill gate to piling', latest: '309 remaining units closed in refreshed workbook', cumulative: '7,694 / 7,694 complete (100.0%)', status: 'On Track', note: 'June 30 Construction Management progress source shows drill-and-backfill complete.' },
      { name: 'Civil grading / cut-fill', remaining: '39% of scope', target: '— No approved daily target in source', latest: '— Daily quantity not reported', cumulative: '61% complete through Jun 19', status: 'On Track', note: 'Current percentage follows Rosario Ruiz Week 24 civil update; it is cumulative progress, not a daily production rate.' },
      { name: 'Internal roads', remaining: '65% of scope', target: '— No approved daily target in source', latest: '— Daily quantity not reported', cumulative: '35% complete through Jun 19', status: 'Critical', note: 'Current percentage follows Rosario Ruiz Week 24 civil update for Areas A-B-C-E.' },
      { name: 'Tracker completion incl. purlins', remaining: '2,273 complete trackers', target: '48 completed tracker rows/day acceleration target', latest: 'Jul 1 tracker/damper activity row: 51 units', cumulative: '213 complete trackers; 493 pre-assembled rows / 2,486 total', status: 'Critical', note: 'This replaces any separate purlin daily-log control. A row is controlled for production through completed tracker status, including purlin readiness for module release.' },
      { name: 'Torque tube installation', remaining: '25,327 tubes', target: '— No approved daily target in source', latest: '— Daily installed quantity not reported', cumulative: '3,542 / 28,869 installed (12.3%)', status: 'Critical', note: 'June 23 Construction Manager workbook cumulative quantity.' },
      { name: 'ITS HDD boring', remaining: '10 of 20 bores', target: 'Minimum 1 completed bore/day', latest: 'Jul 1 daily log: 315 ft boring', cumulative: '10 / 20 bores; 3,554.2 ft installed', status: 'Watch', note: 'The detailed ITS log controls. July 1 shows a major catch-up in boring completion and footage.' },
      { name: 'ITS MV plowing', remaining: '30 of 46 segments', target: 'Minimum 1 completed segment/day', latest: 'Jul 2 status screenshot: 16 segments complete', cumulative: '16 / 46 segments complete (34.0%)', status: 'Watch', note: 'Axel Cano shared the July 2 ITS status showing plowing advanced to 16 completed segments.' },
      { name: 'SET construction', remaining: '91.3% of overall scope', target: '— No approved daily progress target in source', latest: 'Civil/electrical progress through Jul 1 tracker', cumulative: '8.7% overall; 21 complete, 3 in progress, 238 pending', status: 'Critical', note: 'July 1 SET tracker. Civil progress is 33.8%, structural progress is 1.9%, electrical progress is 2.3%.' },
      { name: 'Panel delivery', remaining: '14,230 modules to deliver', target: '— No approved daily delivery target in source', latest: '— Latest daily receipt not reported', cumulative: '157,240 / 171,470 delivered (91.7%)', status: 'On Track', note: 'June 23 Construction Manager workbook cumulative delivery quantity.' },
      { name: 'Module installation', remaining: '171,236 modules', target: '5,531 modules/day acceleration target', latest: 'Jul 3 field note: 234 modules installed', cumulative: '234 modules started by Workforce field note', status: 'Critical', note: 'Treat as field-start progress pending incorporation into the next official production workbook; module work requires fully released tracker rows.' }
    ],
    dailyProductionHistory: [
      { task: 'Pile installation', period: 'Jun 18-Jul 1 measured days', minimum: '560 piles/day', above: 0, below: 9, latest: 'Jul 1 field: 270 piles', note: 'July 1 field report: United 223 piles and Latnovva 47 piles, pending incorporation into the official cumulative workbook. Official cumulative installed production is 17,068 as of the July 1 workbook.', daily: [{ day: 'Jun 18', value: 20, target: 560, unit: 'piles' }, { day: 'Jun 19', value: 79, target: 560, unit: 'piles' }, { day: 'Jun 22', value: 251, target: 560, unit: 'piles' }, { day: 'Jun 23', value: 101, target: 560, unit: 'piles' }, { day: 'Jun 25', value: 370, target: 560, unit: 'piles' }, { day: 'Jun 26', value: 340, target: 560, unit: 'piles' }, { day: 'Jun 29', value: 261, target: 560, unit: 'piles' }, { day: 'Jun 30', value: 234, target: 560, unit: 'piles' }, { day: 'Jul 1', value: 270, target: 560, unit: 'piles' }] },
      { task: 'Tracker production control (incl. purlin completion)', period: 'Jun 17-Jul 1', minimum: '48 tracker units/day', above: 4, below: 9, latest: 'Jul 1: 51 tracker/damper units', note: 'Purlin installation is integrated into this tracker control metric: a tracker row is only counted complete once its purlins are installed. Complete tracker cumulative count is 213, pre-assembled rows are 493, and the latest dated activity row shows 51 units on July 1.', daily: [{ day: 'Jun 17', value: 15, target: 48, unit: 'units' }, { day: 'Jun 18', value: 35, target: 48, unit: 'units' }, { day: 'Jun 19', value: 26, target: 48, unit: 'units' }, { day: 'Jun 20', value: 31, target: 48, unit: 'units' }, { day: 'Jun 21', value: 0, target: 48, unit: 'units' }, { day: 'Jun 22', value: 48, target: 48, unit: 'units' }, { day: 'Jun 23', value: 31, target: 48, unit: 'units' }, { day: 'Jun 24', value: 0, target: 48, unit: 'units' }, { day: 'Jun 25', value: 57, target: 48, unit: 'units' }, { day: 'Jun 26', value: 26, target: 48, unit: 'units' }, { day: 'Jun 29', value: 29, target: 48, unit: 'units' }, { day: 'Jun 30', value: 30, target: 48, unit: 'units' }, { day: 'Jul 1', value: 51, target: 48, unit: 'units' }] },
      { task: 'Module installation', period: 'Jul 3 field start', minimum: '5,531 modules/day', above: 0, below: 1, latest: 'Jul 3: 234 modules', note: 'Workforce field note reports first module installation progress. This is below the full acceleration rate and remains pending workbook incorporation.', daily: [{ day: 'Jul 3', value: 234, target: 5531, unit: 'modules' }] },
      { task: 'ITS MV plowing', period: 'Jun 17-Jul 2', minimum: '1 completed segment/day', above: 6, below: 10, latest: 'Jul 2: 16 cumulative segments complete', note: 'The July 2 ITS status screenshot confirms plowing at 16 of 46 segments, 34.0%.', daily: [{ day: 'Jun 17', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 18', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 19', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 20', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 21', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 22', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 23', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 24', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 25', value: 3, target: 1, unit: 'seg' }, { day: 'Jun 26', value: 4, target: 1, unit: 'seg' }, { day: 'Jun 27', value: 1, target: 1, unit: 'seg' }, { day: 'Jun 28', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 29', value: 2, target: 1, unit: 'seg' }, { day: 'Jun 30', value: 5, target: 1, unit: 'seg' }, { day: 'Jul 1', value: 0, target: 1, unit: 'seg' }, { day: 'Jul 2', value: 1, target: 1, unit: 'seg' }] }
    ],
    successors: [
      { activity: 'Tracker structural assembly', dependency: 'Completed piles by zone/block; final tracker finish after final pile finish', impact: 'Can overlap piling only in released areas. Final tracker structure cannot finish before the revised late-July pile forecast; the August 19 tracker forecast remains provisional and requires 40 completed rows/day.', mitigation: 'Prioritize tracker crews into released workfronts and maintain linked finish-to-finish controls.' },
      { activity: 'Tracker completion including purlins', dependency: 'Completed tracker structure plus both Purlin types confirmed on site', impact: 'The June 17 Purlin load alone cannot complete tracker rows. The first defensible completion wave is after the first Tracker Purlin delivery planned June 23, subject to complete kits and confirmed receipt.', mitigation: 'Confirm each planned load before release, prioritize complete material kits by block, and control daily output through completed tracker rows.' },
      { activity: 'Module installation', dependency: 'Completed tracker rows with both Purlin types installed; final module finish after final purlin finish', impact: 'The earliest defensible first module wave is after June 23, once both Purlin types are physically received and installed on released rows. Final project module completion cannot precede the July 16 planned final Tracker Purlin delivery and subsequent installation.', mitigation: 'Mobilize a controlled module crew only against fully released rows and maintain a block-level tracker/purlin/module constraint log.' },
      { activity: 'DC string wiring / combiner work', dependency: 'Modules set and accessible rows', impact: 'Electrical DC production will be fragmented by workfront availability, increasing crew moves and testing discontinuity.', mitigation: 'Sequence electrical crews by completed inverter block; use partial completion packages and clean turnover boundaries.' },
      { activity: 'Commissioning and MC', dependency: 'Continuous mechanical completion by zone', impact: 'Unconfirmed post receipts and the incomplete purlin plan consume remaining float and make Sep 25 MC more difficult unless early material waves are converted immediately into finished tracker/module work.', mitigation: 'Lock GameChange delivery dates, obtain a site date for the 13,467 unscheduled Purlins, prepare weekend/OT acceleration, and track daily pile burn versus confirmed receipts.' }
    ],
    schedule: [
      { activity: 'D&F Pre-Drilling', contractor: 'Kalamazoo Excavating', start: '2026-05-06', end: '2026-06-30', status: 'Complete', note: 'The June 30 Construction Management PROGRESS sheet shows 7,694 of 7,694 drill-and-backfill units complete.' },
      { activity: 'Current pile delivery burn', contractor: 'ECCS / LATNOVVA / United', start: '2026-06-16', end: '2026-07-01', status: 'Critical', note: 'The refreshed official workbook reports 17,068 installed and 19,432 delivered piles, leaving a 2,364-pile buffer, about 4.2 days at the 560/day acceleration capacity.' },
      { activity: 'June 23 recorded delivery wave', contractor: 'GameChange / Logistics', start: '2026-06-23', end: '2026-06-23', status: 'Confirmed', note: 'The refreshed official workbook records 658 additional delivered piles and receipt lines for 21,672 tracker purlins, 20,251 purlin strips, 640 row tubes, and 2,760 heavy squeeze splices.' },
      { activity: 'June 24 scheduled delivery wave', contractor: 'GameChange / Logistics', start: '2026-06-24', end: '2026-06-24', status: 'Critical', note: 'Shreeya scheduled 6 trucks: 90 Light Green posts, 7,956 tracker purlins, 5,520 heavy splices, 7,840 saddle brackets, and 272 row tubes. Count as pending until POD/site receipt.' },
      { activity: 'June 30 confirmed delivery sequence', contractor: 'GameChange / NTG / Landstar', start: '2026-06-30', end: '2026-06-30', status: 'Critical', note: 'Shreeya confirmed 12 timed loads for June 30 from 7:00 am to 2:30 pm. MRSU8536763 is a carryover from June 29 after late loading in Los Angeles. Count as scheduled/confirmed until POD/site receipt is logged.' },
      { activity: 'July 2 confirmed delivery sequence', contractor: 'GameChange / NTG / Landstar', start: '2026-07-02', end: '2026-07-02', status: 'Critical', note: 'Shreeya confirmed 9 named loads for July 2. Count as scheduled until POD/site receipt, material type, and actual quantities are logged.' },
      { activity: 'July 3 confirmed delivery sequence', contractor: 'GameChange / NTG', start: '2026-07-03', end: '2026-07-03', status: 'Critical', note: 'Shreeya confirmed 6 named NTG loads for July 3: TCLU1477450, YMMU6239469, EITU9400207, TXGU6059112, TRHU8675801, and TRHU6565282. The email shows a blank 10:45 appointment line; confirm whether it was used.' },
      { activity: 'Delivery receiving-cap control', contractor: 'GameChange / Greensol Logistics', start: '2026-06-23', end: '2026-07-06', status: 'Critical', note: "Manuel's latest delivery position requests July 3 and July 6 as piles-only where possible; following days can receive up to 14 pile loads/day plus 8 racking loads/day, still subject to appointment discipline and POD/site receipt." },
      { activity: 'United Zone F mobilization and pile-spot marking', contractor: 'United', start: '2026-06-15', end: '2026-06-21', status: 'Mobilizing', note: 'United replaces JB Solar for Zone F. Complete pile-spot marking, crew and equipment mobilization, safety onboarding, access readiness, and workfront release before ramming.' },
      { activity: 'United Zone F pile ramming start', contractor: 'United', start: '2026-06-22', end: '2026-06-22', status: 'Critical', note: 'United starts pile ramming on June 22, subject to the delayed pile delivery, completed marking, access, and released workfronts.' },
      { activity: 'Overall pile installation acceleration', contractor: 'All pile contractors', start: '2026-06-22', end: '2026-07-28', status: 'Critical', note: 'The official workbook leaves 14,284 piles. July 1 field output was 270 piles versus the 560/day target; July 2-3 field notes confirm output remains constrained by Area F hard soil, damaged rigs, and the need for pre-drilling or more effective machines.' },
      { activity: 'Tracker Structural Assembly', contractor: 'ECCS', start: '2026-06-08', end: '2026-08-19 provisional', status: 'At Risk', note: 'Official cumulative counts are 213 complete trackers and 493 pre-assembled rows (Jul 1 workbook). Golden Row and purlin activity have started, but final tracker completion must still remain after final pile completion.' },
      { activity: 'ITS HDD boring', contractor: 'ITS', start: '2026-06-12', end: '2026-08-15', status: 'Active', note: 'Ten of 20 bores are complete with 3,554.2 ft installed through the July 1 ITS workbook. July 1 daily log shows 315 ft boring.' },
      { activity: 'ITS MV cable plowing', contractor: 'ITS', start: '2026-06-25', end: '2026-08-15', status: 'Active', note: 'Axel Cano July 2 status screenshot confirms 16 of 46 plow segments complete, 34.0%.' },
      { activity: 'Control building foundation and delivery gate', contractor: 'AB Power / SET team', start: '2026-06-20', end: '2026-07-10', status: 'Critical', note: 'July 1 SET tracker shows 8.7% overall progress. Control-building FAT was reported passed in the July 1 field chat, and delivery remains tracked to the July 7 committed date.' },
      { activity: 'SET equipment required-on-site gate', contractor: 'SET team / Procurement / Suppliers', start: '2026-06-24', end: '2026-07-10', status: 'Critical', note: 'July 1 SET supply tracker still shows transformer and control building in fabrication; several electrical items remain committed after the July 10 required-on-site gate and require procurement acceleration.' },
      { activity: 'Inverter foundation readiness', contractor: 'EPC / Civil / Electrical', start: '2026-06-20', end: '2026-07-25 provisional', status: 'Critical', note: 'The 23 inverter units are expected to land at the end of July, not the beginning of July. All inverter pile foundations must be ready before the first inverter arrives.' },
      { activity: 'Inverter Installation', contractor: 'EPC / OEM', start: '2026-07-27', end: '2026-09-15', status: 'Confirmed', note: '23 x 4.2 MW units. Installation is separated from the SET/control-building scope and depends on completed inverter pile foundations before first delivery.' },
      { activity: 'Purlin and racking delivery sequence', contractor: 'GameChange / Logistics', start: '2026-06-17', end: '2026-07-16', status: 'Critical', note: 'The June 23 workbook records 21,672 tracker purlins plus purlin strips, row tubes, and splices. Remaining rolling deliveries continue through the July 16 final planned tracker-purlin date; complete kits require receipt and block allocation.' },
      { activity: 'Workforce module crew mobilization', contractor: 'Workforce', start: '2026-06-29', end: '2026-07-06', status: 'Critical', note: 'Workforce is expected to land June 29 with approximately 22 workers. Use this as mobilization/ramp only; module erection starts only against purlin-complete, QA-released rows.' },
      { activity: 'Tracker completion including purlins', contractor: 'GameChange / ECCS', start: '2026-06-23', end: '2026-09-18', status: 'Critical', note: 'Purlin work is controlled inside the completed tracker-row metric from July 3 forward. June 23 receipts must be allocated into complete block kits and released workfronts.' },
      { activity: 'Final module installation completion', contractor: 'Workforce', start: '2026-07-03', end: '2026-10-09', status: 'Critical', note: 'Workforce field note reports the first 234 modules installed. The activity has started, but full-field production still depends on released tracker rows and the module crew ramp.' },
      { activity: 'DC Wire / LV Installation', contractor: 'East Carolina + Self-Perform', start: '2026-07-07', end: '2026-10-12 provisional', status: 'Critical', note: 'The LV scope will use an aerial messenger-wire-supported harness / BLA-style installation from tracker rows to the junction boxes. First Chemik pre-tailored cable reels are expected July 7, and East Carolina plus self-perform crews should start the pull, support, and terminations immediately behind released module workfronts by block.' },
      { activity: 'Electrical Pre-Commissioning', contractor: 'EPC + OEMs', start: '2026-09-15', end: '2026-11-01', status: 'Planned', note: 'Zonal energization after inverter, MV/HDD, tracker, module, and DC/LV turnover by block.' }
    ],
    fieldResourceSnapshots: [
      { label: 'Jun 17 actual', week: 'W25', people: 136, color: '#b53030', offset: -18 },
      { label: 'Jun 30 official', week: 'W27', people: 148, color: '#2769a8', offset: 18 }
    ],
    actualResources: [
      { contractor: 'ECCS', people: 47.5, label: '47-48 people' },
      { contractor: 'United', people: 18, label: '16-20 people' },
      { contractor: 'Latnovva', people: 17, label: '17 people' },
      { contractor: 'ITS', people: 14, label: '14 crew' },
      { contractor: 'Workforce', people: 12, label: '12 people' }
    ],
    resourcePlan: [
      { label: 'Total site resources', actual: 148, target: 105, targetLabel: 'Acceleration peak 95-105', note: 'Includes field labor plus management/QC/HSE; actual is the June 30 official manpower table from the Jul 1 Delivery/Mechanical workbook.' },
      { label: 'Tracker / purlin crew', actual: 47, target: 45, targetLabel: '38 avg / 40-45 peak', note: 'ECCS visible field resources are compared with the tracker/purlin acceleration target.' },
      { label: 'Module crew Phase 1', actual: 0, committed: 22, target: 22, targetLabel: '22 by Jul 7', note: 'Workforce is expected to land June 29 with about 22 workers for the rolling start.' },
      { label: 'Module full-field crew', actual: 0, committed: 22, target: 40, targetLabel: '40 by Jul 13+', note: 'Phase 2 reinforcement adds 18 workers to reach the full-field module gate.' },
      { label: 'Greensol site team', actual: 24, target: 24, targetLabel: '15 staff + 9 labor', note: 'User-provided fixed Greensol site staffing basis.' }
    ],
    mechanicalManpowerLoad: [
      { week: 'Jun 22', pile: 9, tracker: 16, module: 0, management: 13, total: 38 },
      { week: 'Jun 29', pile: 10, tracker: 28, module: 0, management: 13, total: 51 },
      { week: 'Jul 6', pile: 10, tracker: 35, module: 0, management: 13, total: 58 },
      { week: 'Jul 13', pile: 10, tracker: 42, module: 22, management: 13, total: 87 },
      { week: 'Jul 20', pile: 10, tracker: 50, module: 37, management: 13, total: 110 },
      { week: 'Jul 27', pile: 10, tracker: 42, module: 40, management: 13, total: 105 },
      { week: 'Aug 3', pile: 0, tracker: 42, module: 40, management: 13, total: 95 },
      { week: 'Aug 10', pile: 0, tracker: 42, module: 40, management: 13, total: 95 },
      { week: 'Aug 17', pile: 0, tracker: 42, module: 40, management: 13, total: 95 },
      { week: 'Aug 24', pile: 0, tracker: 42, module: 40, management: 13, total: 95 },
      { week: 'Sep 7', pile: 0, tracker: 42, module: 40, management: 13, total: 95 },
      { week: 'Sep 14', pile: 0, tracker: 42, module: 40, management: 13, total: 95 },
      { week: 'Sep 21', pile: 0, tracker: 0, module: 40, management: 10, total: 50 },
      { week: 'Sep 28', pile: 0, tracker: 0, module: 40, management: 10, total: 50 },
      { week: 'Oct 5', pile: 0, tracker: 0, module: 0, management: 5, total: 5 }
    ],
    mechanicalManpowerMilestones: [
      { week: 'Jun 22', label: 'Acceleration plan starts', color: '#b53030', row: 0 },
      { week: 'Jul 27', label: 'Piles complete · Jul 28', color: '#66716d', row: 1 },
      { week: 'Sep 14', label: 'Trackers / purlins · Sep 18', color: '#168a5b', row: 0 },
      { week: 'Oct 5', label: 'Modules · Oct 9', color: '#2769a8', row: 1 }
    ],
    personnelOutlook: [
      { week: 'W22', date: 'May 25', people: 135 },
      { week: 'W23', date: 'Jun 1', people: 281 },
      { week: 'W24', date: 'Jun 8', people: 281 },
      { week: 'W25', date: 'Jun 15', people: 281 },
      { week: 'W26', date: 'Jun 22', people: 229 },
      { week: 'W27', date: 'Jun 29', people: 228 },
      { week: 'W28', date: 'Jul 6', people: 228 },
      { week: 'W29', date: 'Jul 13', people: 228 },
      { week: 'W30', date: 'Jul 20', people: 310 },
      { week: 'W31', date: 'Jul 27', people: 220 },
      { week: 'W32', date: 'Aug 3', people: 255 },
      { week: 'W33', date: 'Aug 10', people: 255 },
      { week: 'W34', date: 'Aug 17', people: 205 },
      { week: 'W35', date: 'Aug 24', people: 205 },
      { week: 'W36', date: 'Aug 31', people: 205 },
      { week: 'W37', date: 'Sep 7', people: 205 },
      { week: 'W38', date: 'Sep 14', people: 205 },
      { week: 'W39', date: 'Sep 21', people: 155 },
      { week: 'W40', date: 'Sep 28', people: 155 },
      { week: 'W41', date: 'Oct 5', people: 130 },
      { week: 'W42', date: 'Oct 12', people: 130 },
      { week: 'W43', date: 'Oct 19', people: 75 },
      { week: 'W44', date: 'Oct 26', people: 75 },
      { week: 'W45', date: 'Nov 2', people: 75 },
      { week: 'W46', date: 'Nov 9', people: 75 },
      { week: 'W47', date: 'Nov 16', people: 0 }
    ],
    milestones: [
      { name: 'Mechanical Completion', target: 'Sep 25, 2026', forecast: 'Oct 10-15, 2026 provisional', status: 'Critical', note: 'The revised late-July pile and provisional August 19 tracker forecasts leave no acceleration margin; MC still depends on full purlin completion by September 18 and modules by October 9.' },
      { name: 'Provisional Interconnection', target: 'Oct 16, 2026', forecast: 'Oct 20-25, 2026', status: 'Critical', note: 'Depends on revised MC; utility/offtake renegotiation likely required.' },
      { name: 'Commercial Operation Date', target: 'Nov 9, 2026', forecast: 'Nov 5-9, 2026', status: 'High', note: 'Feasible only in optimistic scenario; zero float remains.' },
      { name: 'Substantial Completion', target: 'Nov 30, 2026', forecast: 'Nov 30, 2026', status: 'Watch', note: 'Still achievable if COD is protected and outdoor work closes before weather stop.' }
    ],
    risks: [
      { title: 'Pile stock is a short-duration buffer, and July 2-3 loads still need POD confirmation', level: 'Critical', owner: 'GameChange / Shreeya Devkota / Karina Mucino / Manuel Ramirez / Audelio Zuniga', note: 'The refreshed workbook shows 2,364 piles available above installed production, about 4.2 days at the 560-pile/day acceleration capacity. Shreeya confirmed 9 named loads for July 2 and 6 named NTG loads for July 3 — treat these as scheduled until POD/site receipt, material type, and actual quantities are confirmed. Confirm receipts and subcontractor allocation every day.' },
      { title: 'Area F hard soil is limiting pile output', level: 'Critical', owner: 'Audelio Zuniga / United / Manuel Ramirez', note: 'July 2-3 WhatsApp field notes keep pile output well below the 560/day target. The team discussed Kalamazoo support for roughly 3,000 pre-drills, 4-ft pilot drilling tests, stronger machines, and/or more effective ramming machines to protect the July 28 pile gate.' },
      { title: 'Complete tracker kits control module release', level: 'Critical', owner: 'GameChange / ECCS / Manuel Ramirez', note: 'Manuel confirmed purlins will be reported as complete trackers once installed. Workforce has started modules with 234 reported, but module production still needs fully complete, QA-cleared tracker rows.' },
      { title: 'SET foundation, delivery dates, and equipment commitments all need closure', level: 'Critical', owner: 'Axel Cano / AB Power / Karina Mucino / Joshua Spalding / Project Management', note: 'July 1 SET tracker shows 8.7% overall progress. Control-building FAT was reported passed, but the July 7 delivery gate still must stay aligned with foundation readiness. The transformer, control building, and structural steel remain in fabrication, and several electrical items show committed dates after the July 10 required-on-site gate — a supplier acceleration plan is required.' },
      { title: 'ITS plowing must sustain the first production jump', level: 'Watch', owner: 'ITS / Audelio Zuniga / Angel Urbina', note: 'July 2 ITS status confirms 16 of 46 plow segments complete. Keep daily LF and segment reporting active while closing the remaining 10 bores.' },
      { title: 'Area F/G civil release controls mechanical access', level: 'Critical', owner: 'Rosario Ruiz / Audelio Zuniga / Lounsbury', note: 'June 26 field note sets Area E completion for June 30 and Area F start for July 1, while Area G basins 66/70 continue. These fronts must release quickly to avoid starving mechanical crews.' }
    ]
  };
