'use strict';
// Murch dashboard data - update THIS file for daily changes
const assetVersion = '20260627-whatsapp-field';
const assetBase = 'https://claped71.github.io/murch-dashboard/';
function asset(path) { return assetBase + path + '?v=' + assetVersion; }
function assetFallback(path) { return assetBase + path; }
window.MURCH_DATA = {
    scope: [
      { title: 'EPC Management', metric: 'Turnkey', note: 'Project management, safety, QC, contractor deliverables, owner reporting, permitting support, and trade coordination through completion.' },
      { title: 'Civil and Environmental', metric: 'G released', note: 'Rosario Week 26 email says Area G is released for pile driving and material distribution; Area G cut/fill starts after basin completion.' },
      { title: 'Mechanical BOS', metric: '31,352 piles', note: 'Pile driving, D&F pre-drilling where required, GameChange SAT tracker assembly, purlin install, and module placement.' },
      { title: 'Electrical BOS', metric: 'ITS plowing on site', note: 'MV collection, HDD, plowing, grounding, DC string and combiner wiring, LV/AC works, inverter installation, SCADA, and testing. Joshua Spalding reported the ITS plowing machine arrived on June 19.' },
      { title: 'Procurement', metric: '171,470 modules', note: 'Panels, racking, purlins, actuators, controllers, cables, inverter stations, combiner boxes, and SET equipment.' },
      { title: 'Commissioning', metric: 'PIS Oct 16', note: 'Cold commissioning, energization, tracker testing, inverter start-up, PR test path, punch list, COD, and substantial completion.' }
    ],
    photos: [
      { src: asset('assets/recent/recent-26.jpg'), fallbackSrc: assetFallback('assets/recent/recent-26.jpg'), date: 'July 1, 2026', title: 'Control-building access platform fabrication', note: 'Factory photo of yellow access platform/stair components for the control-building package; FAT status was reported as passed in the July 1 field chat.' },
      { src: asset('assets/recent/recent-27.jpg'), fallbackSrc: assetFallback('assets/recent/recent-27.jpg'), date: 'July 1, 2026', title: 'Control-building platform and handrail detail', note: 'Additional factory view of control-building access-platform details, supporting the July 7 control-building delivery gate.' },
      { src: asset('assets/recent/recent-21.jpg'), fallbackSrc: assetFallback('assets/recent/recent-21.jpg'), date: 'June 25, 2026', title: 'Golden Row installation', note: 'Golden Row tracker/racking installation shared by Audelio Zuniga, documenting the first representative mechanical completion sequence ahead of module release.' },
      { src: asset('assets/recent/recent-23.jpg'), fallbackSrc: assetFallback('assets/recent/recent-23.jpg'), date: 'June 25, 2026', title: 'ITS MV plowing workfront', note: 'MV cable/plowing workfront activity, supporting the ITS start-up sequence that must now convert into measured feet and completed segments.' },
      { src: asset('assets/recent/recent-22.jpg'), fallbackSrc: assetFallback('assets/recent/recent-22.jpg'), date: 'June 25, 2026', title: 'SET control-building reference photo', note: 'Control-building visual shared by Axel Cano. The June 26 SET workbook still carries the control building as in fabrication with a July 7 committed date, so delivery remains a tracked gate.' },
      { src: asset('assets/recent/recent-24.jpg'), fallbackSrc: assetFallback('assets/recent/recent-24.jpg'), date: 'June 24, 2026', title: 'Civil/fence workfront conditions', note: 'Field view of civil and fencing workfront conditions supporting Area E/F/G release sequencing.' },
      { src: asset('assets/recent/recent-25.jpg'), fallbackSrc: assetFallback('assets/recent/recent-25.jpg'), date: 'June 25, 2026', title: 'Purlin slot detail for module-fit control', note: 'Golden Row detail photo used as quality evidence: module spacing must be measured during tightening because slot tolerance can slow module installation.' },
      { src: asset('assets/recent/recent-20.jpg'), fallbackSrc: assetFallback('assets/recent/recent-20.jpg'), date: 'June 25, 2026', title: 'Golden Row installation', note: 'Field crew installing the Golden Row tracker/racking assembly, documenting the first representative mechanical installation sequence.' },
      { src: asset('assets/recent/recent-14.jpg'), fallbackSrc: assetFallback('assets/recent/recent-14.jpg'), date: 'June 19, 2026', title: 'Racking workfront beside stabilized access', note: 'Installed pile and racking lines beside the project access road, documenting active mechanical workfront conditions.' },
      { src: asset('assets/recent/recent-13.jpg'), fallbackSrc: assetFallback('assets/recent/recent-13.jpg'), date: 'June 19, 2026', title: 'Tracker and racking installation', note: 'Wide field view of active tracker and racking installation, showing the scale of the released mechanical workfront.' },
      { src: asset('assets/recent/recent-15.jpg'), fallbackSrc: assetFallback('assets/recent/recent-15.jpg'), date: 'June 19, 2026', title: 'ITS MV boring operation', note: 'Excavator and crew supporting the ITS medium-voltage boring scope at the wooded crossing workfront.' },
      { src: asset('assets/recent/recent-16.jpg'), fallbackSrc: assetFallback('assets/recent/recent-16.jpg'), date: 'June 19, 2026', title: 'MV conduit handling and bore preparation', note: 'ITS crew handling conduit and preparing the bore workfront for the underground medium-voltage crossing.' },
      { src: asset('assets/recent/recent-17.jpg'), fallbackSrc: assetFallback('assets/recent/recent-17.jpg'), date: 'June 19, 2026', title: 'MV boring materials staged in Area F', note: 'Conduit and boring materials staged at the Area F crossing, showing the physical preparation for the ITS installation sequence.' },
      { src: asset('assets/recent/recent-18.jpg'), fallbackSrc: assetFallback('assets/recent/recent-18.jpg'), date: 'June 19, 2026', title: 'Wooded crossing workfront preparation', note: 'Compact equipment clearing and preparing access at the wooded MV crossing before boring and conduit installation.' },
      { src: asset('assets/recent/recent-19.jpg'), fallbackSrc: assetFallback('assets/recent/recent-19.jpg'), date: 'June 19, 2026', title: 'Substation foundation formwork', note: 'Substation foundation and containment formwork under construction, documenting current SET civil progress.' },
      { src: asset('assets/recent/recent-1.jpg'), fallbackSrc: assetFallback('assets/recent/recent-1.jpg'), date: 'June 19, 2026', title: 'ITS plowing machine arrival', note: 'Joshua Spalding reported that the ITS plowing machine arrived on site for the MW cable scope; this photo shows the equipment staged and ready for electrical mobilization.' },
      { src: asset('assets/recent/recent-4.jpg'), fallbackSrc: assetFallback('assets/recent/recent-4.jpg'), date: 'June 17, 2026', title: 'Tracker workfront conditions', note: 'June 17 site photo showing muddy tracker rows, standing water, and access conditions affecting mechanical and follow-on workfront continuity.' },
      { src: asset('assets/recent/recent-7.jpg'), fallbackSrc: assetFallback('assets/recent/recent-7.jpg'), date: 'June 11, 2026', title: 'Environmental controls and field support', note: 'Civil and environmental view showing stabilized access, sediment-control wattles, drainage protection, and support facilities.' },
      { src: asset('assets/recent/recent-8.jpg'), fallbackSrc: assetFallback('assets/recent/recent-8.jpg'), date: 'June 3, 2026', title: 'Aerial civil and laydown context', note: 'Drone view showing the broader civil layout, access roads, laydown area, and surrounding project workfronts.' },
      { src: asset('assets/recent/recent-11.jpg'), fallbackSrc: assetFallback('assets/recent/recent-11.jpg'), date: 'May 26, 2026', title: 'Basin and road stabilization', note: 'Representative civil/environmental photo showing stabilized basin slopes and access-road construction.' }
    ],
    weeklyPlan: [
      { area: '<u>Pile production acceleration — Zones B / F / D-G</u><span style="background:#b53030;color:#fff;padding:1px 6px;border-radius:3px;font-size:10px;font-weight:700;margin-left:6px">CRITICAL</span>', target: 'Recover ramming output: 13,651 piles remain to the Jul 28 pile-complete gate. July 6 field output was 307 piles plus 1 inverter pile, still below the 560/day acceleration control rate.', minimum: '>= 560 piles/day sustained; July 6 field output reached about 55% of requirement', gate: 'Area F hard soil, rig availability, and daily pile-stock re-feed. United reports 7 ramming machines; Latnovva had one damaged rig and one rig being assembled.', owners: 'LATNOVVA / United | Audelio Zuniga | Manuel Ramirez | Joshua Spalding' },
      { area: '<u>GameChange tracker-material deliveries</u><span style="background:#b53030;color:#fff;padding:1px 6px;border-radius:3px;font-size:10px;font-weight:700;margin-left:6px">CRITICAL</span>', target: 'Confirm POD/site receipt for the Jul 7 eleven-load sequence and protect the Jul 16 final tracker-material delivery gate.', minimum: 'From Jul 7 receive up to 14 pile loads/day plus 8 racking loads/day if appointments and offloading resources hold.', gate: 'Tracker material receipts remain a project gate, but daily production is controlled through completed tracker rows, not a separate purlin daily log.', owners: 'GameChange (Shreeya Devkota) | Manuel Ramirez | Karina Mucino' },
      { area: '<u>Module installation ramp — Area A</u><span style="background:#b53030;color:#fff;padding:1px 6px;border-radius:3px;font-size:10px;font-weight:700;margin-left:6px">CRITICAL</span>', target: 'Module erection is underway. Workforce reported 17 people and 780 modules on July 6, pending official workbook incorporation.', minimum: 'Reach >= 2,000 modules/day by Friday Jul 10; the acceleration plan requires 5,531/day full-field from mid-July', gate: 'QA-released complete tracker rows + measured module-spacing QC control (Golden Row slot-tolerance finding) + crew ramp on schedule.', owners: 'Workforce | Audelio Zuniga | Daniel Morilla (QA/QC) | Manuel Ramirez' },
      { area: 'Tracker assembly and completed row release', target: 'Recover from the July 6 no-progress report, close Area A4 release, open Area C, and keep Steps 1-6 rolling into C/E.', minimum: '>= 48 tracker units/day sustained all week and ramp toward 40 completed rows/day', gate: 'Complete tracker kits allocated by block and same-week QA turnover of finished rows.', owners: 'ECCS | Audelio Zuniga | Manuel Ramirez' },
      { area: 'Civil Area F/G release and internal roads', target: 'Finish Area G basins, then start Area G cut/fill. Rosario Ruiz reported Area G released for pile driving and material distribution.', minimum: 'Daily confirmed grading production in Area G after basin closeout; roads remain the controlling logistics constraint', gate: 'Civil access, fencing gates, and drainage release ahead of the mechanical fronts.', owners: 'Lounsbury / Hurricane / Topland | Rosario Ruiz | Audelio Zuniga' },
      { area: 'Electrical MV plowing and HDD closeout', target: 'Sustain plowing production (30 of 46 segments remaining) and continue closing the remaining 10 bores.', minimum: '>= 1 plow segment/day and >= 1 completed bore/day with measured footage reporting', gate: 'Crossing approvals, access continuity, and equipment availability. July 6 daily production was 0 ft for boring and plowing.', owners: 'ITS | Angel Urbina | Joshua Spalding' },
      { area: 'SET control building and inverter foundations', target: 'Receive the control building on the Jul 7 committed date (FAT passed Jul 1), hold the Jul 10 required-on-site gate, and complete inverter pile foundations before the end-July arrival of the 23 inverter units.', minimum: '100% control-building foundation accepted; inverter foundations released ahead of first delivery', gate: 'Procurement acceleration on SET items still committed after the Jul 10 gate.', owners: 'AB Power / SET team | Axel Cano | Joshua Spalding | Karina Mucino' },
      { area: 'LV aerial-system readiness', target: 'Receive the first Chemik pre-tailored cable reels on Jul 7 and start East Carolina plus self-perform crews immediately behind released module blocks.', minimum: '>= 1 first-batch cable package received and >= 1 LV block package released by Jul 7', gate: 'Released module areas and East Carolina plus self-perform crew readiness.', owners: 'East Carolina / Greensol Self-Perform | Angel Urbina | Luis Romero | Karina Mucino' }
    ],
    civilKpis: [
      { title: 'Civil field progress', metric: 'Week 26', note: 'Rosario Ruiz Week 26 email dated July 3 and sent July 6 controls the latest civil workfront note.' },
      { title: 'Area G release', metric: 'Released', note: 'Rosario reports that once Area G basins are finished, cut/fill will start there; Area G is also released for pile driving and material distribution.' },
      { title: 'SET tracker', metric: '8.7% overall', note: 'The July 6 SET tracker remains 21 complete activities, 3 in progress, and 238 pending. Civil progress is 33.8%, structural progress is 1.9%, and electrical progress is 2.3%.' }
    ],
    civilActivities: [
      { activity: 'Earthworks cut / fill', company: 'Lounsbury', done: 61, remaining: 39, status: 'Active', note: 'Latest quantified percentage remains Week 24. Rosario Week 26 adds that Area G cut/fill starts after the Area G basins are finished.' },
      { activity: 'Perimeter fence', company: 'Hurricane', done: 76, remaining: 24, status: 'Active', note: 'Week 24 baseline remains 76%. June 26 field note says Areas A, B, C, E, EW and F are complete, with gates next.' },
      { activity: 'Sediment basins / environmental controls', company: 'Lounsbury / ECS', done: 47, remaining: 53, status: 'At Risk', note: 'Latest quantified percentage remains Week 24. Rosario Week 26 states Area G basins must finish before Area G cut/fill starts.' },
      { activity: 'Internal roads', company: 'Topland', done: 35, remaining: 65, status: 'Critical', note: 'Week 24 civil update shows roads in Areas A-B-C-E at 35% executed; roads continue to control logistics access.' },
      { activity: 'PS foundations', company: 'United', done: 38, remaining: 62, status: 'Critical', note: 'Week 24 civil update reports PS foundations at 38% executed, with work planned through August 10.' },
      { activity: 'Foundation SET', company: 'AB Power', done: 8.7, remaining: 91.3, status: 'Active', note: 'July 6 SET workbook shows overall substation progress at 8.7%; civil progress is 33.8%, structural progress is 1.9%, and electrical progress is 2.3%.' }
    ],
    contractors: [
      { name: 'LATNOVVA / assigned areas', scope: 19260, installed: 11925, remaining: 7335, done: 61.9, zones: 'Zones A, B, C, D, G, EW + shared Area E control', status: 'Watch', note: "Area-based control allocation only; it is not a new manpower or subcontractor headcount report." },
      { name: 'ECCS / Area E control', scope: 4434, installed: 4066, remaining: 368, done: 91.7, zones: 'Area E shared tracker workfront', status: 'On Track', note: "Area-based control allocation used only so dashboard totals reconcile with Audelio's July 6 official installed-production basis." },
      { name: 'United', scope: 7658, installed: 1710, remaining: 5948, done: 22.3, zones: 'Zone F', status: 'Active', note: 'United Zone F production is counted in the refreshed official workbook; continuity depends on hard-soil mitigation and confirmed pile deliveries.' },
      { name: 'Project Total', scope: 31352, installed: 17701, remaining: 13651, done: 56.5, zones: "All zones | Construction Manager report", status: 'Critical', note: "Audelio / Construction Manager July 6 Delivery/Mechanical workbook is the official installed-production basis." }
    ],
    zones: [
      { zone: 'Zone A', contractor: 'Latnovva', scope: 3834, installed: 3831, remaining: 3, done: 99.9, status: 'On Track', note: 'June 30 Const. Management workbook; nearly complete.' },
      { zone: 'Zone C', contractor: 'Latnovva', scope: 2946, installed: 2946, remaining: 0, done: 100.0, status: 'Complete', note: 'July 6 Const. Management workbook; zone complete.' },
      { zone: 'Zone E', contractor: 'ECCS / Latnovva', scope: 8456, installed: 8012, remaining: 444, done: 94.7, status: 'Active', note: 'July 6 Delivery / Mechanical roll-up.' },
      { zone: 'Zone EW', contractor: 'Latnovva', scope: 846, installed: 823, remaining: 23, done: 97.3, status: 'Active', note: 'June 30 Const. Management workbook; nearly complete.' },
      { zone: 'Zone B', contractor: 'Latnovva', scope: 2788, installed: 379, remaining: 2409, done: 13.6, status: 'Active', note: 'July 6 Delivery / Mechanical roll-up.' },
      { zone: 'Zone D', contractor: 'TBD / Latnovva', scope: 1468, installed: 0, remaining: 1468, done: 0, status: 'Material Hold', note: '2nd-50% work; no start before June 22 material arrivals.' },
      { zone: 'Zone F', contractor: 'United', scope: 7658, installed: 1710, remaining: 5948, done: 22.3, status: 'Active', note: 'July 6 Delivery / Mechanical roll-up shows Zone F production continuing, but hard soil remains the critical productivity risk.' },
      { zone: 'Zone G', contractor: 'Latnovva', scope: 3356, installed: 0, remaining: 3356, done: 0, status: 'Active', note: 'Assigned to Latnovva. Rosario Ruiz Week 26 email says Area G is released for pile driving and material distribution; civil cut/fill starts after Area G basins are finished.' }
    ],
    production: [
      { name: 'Project pile installation', remaining: '13,651 piles', target: '560 piles/day acceleration capacity', latest: 'Jul 6 field note: United 307 piles + 1 inverter pile; Latnovva 0; ECCS no work', cumulative: '17,701 / 31,352 installed (56.5%)', status: 'Critical', note: 'Installed production follows Audelio / Construction Manager workbook. July 6 field output remains below the acceleration target and is concentrated in Area F.' },
      { name: 'Pile delivery / site stock', remaining: '5,843 piles undelivered', target: 'Receipts must exceed 560 piles/day burn', latest: 'Jul 6 workbook: delivered piles increased to 25,509', cumulative: '25,509 delivered; 7,808 available above installed', status: 'Watch', note: 'Available stock equals delivered piles less officially installed piles. The current buffer covers about 13.9 production days at the acceleration-capacity assumption.' },
      { name: 'Drill and backfill', remaining: '0 pre-drills', target: 'Maintain no drill/backfill gate to piling', latest: 'All remaining units closed in refreshed workbook', cumulative: '7,694 / 7,694 complete (100.0%)', status: 'On Track', note: 'July 6 Construction Management progress source shows drill-and-backfill complete.' },
      { name: 'Civil grading / cut-fill', remaining: '39% of scope', target: '— No approved daily target in source', latest: 'Week 26 email: Area G cut/fill starts after basins finish', cumulative: '61% complete through latest quantified civil baseline', status: 'On Track', note: 'Current percentage follows Rosario Ruiz civil baseline; Week 26 adds Area G release for pile driving and material distribution.' },
      { name: 'Internal roads', remaining: '65% of scope', target: '— No approved daily target in source', latest: '— Daily quantity not reported', cumulative: '35% complete through latest quantified civil baseline', status: 'Critical', note: 'Current percentage follows Rosario Ruiz civil baseline for Areas A-B-C-E; roads continue to control logistics access.' },
      { name: 'Tracker completion incl. purlins', remaining: '2,273 complete trackers', target: '48 completed tracker rows/day acceleration target', latest: 'Jul 6 WhatsApp: no tracker progress; Area A4 release planned next', cumulative: '213 complete trackers; 493 pre-assembled rows / 2,486 total', status: 'Critical', note: 'This replaces any separate purlin daily-log control. A row is controlled for production through completed tracker status, including purlin readiness for module release.' },
      { name: 'Torque tube installation', remaining: '25,327 tubes', target: '— No approved daily target in source', latest: '— Daily installed quantity not reported', cumulative: '3,542 / 28,869 installed (12.3%)', status: 'Critical', note: 'June 23 Construction Manager workbook cumulative quantity.' },
      { name: 'ITS HDD boring', remaining: '10 of 20 bores', target: 'Minimum 1 completed bore/day', latest: 'Jul 6 daily log: 0 ft boring', cumulative: '10 / 20 bores; 3,554.2 ft installed', status: 'Watch', note: 'The detailed ITS log controls. Week of Jun 30-Jul 6 shows 630 ft of boring.' },
      { name: 'ITS MV plowing', remaining: '30 of 46 segments', target: 'Minimum 1 completed segment/day', latest: 'Jul 6 daily log: 0 ft plowing', cumulative: '16 / 46 segments complete; 43,128 ft installed', status: 'Watch', note: 'July 6 ITS workbook reports 16 of 46 plow segments complete and 19,068 ft plowed in the Jun 30-Jul 6 week.' },
      { name: 'SET construction', remaining: '91.3% of overall scope', target: '— No approved daily progress target in source', latest: 'Civil/electrical progress through Jul 6 tracker', cumulative: '8.7% overall; 21 complete, 3 in progress, 238 pending', status: 'Critical', note: 'July 6 SET tracker. Civil progress is 33.8%, structural progress is 1.9%, electrical progress is 2.3%.' },
      { name: 'Panel delivery', remaining: '14,230 modules to deliver', target: '— No approved daily delivery target in source', latest: '— Latest daily receipt not reported', cumulative: '157,240 / 171,470 delivered (91.7%)', status: 'On Track', note: 'June 23 Construction Manager workbook cumulative delivery quantity.' },
      { name: 'Module installation', remaining: 'Pending official workbook update', target: '5,531 modules/day acceleration target', latest: 'Jul 6 field note: 780 modules reported by Workforce', cumulative: '780 modules field-reported, pending official workbook incorporation', status: 'Critical', note: 'Treat as field-start progress pending incorporation into the next official production workbook; module work requires fully released tracker rows.' }
    ],
    dailyProductionHistory: [
      { task: 'Pile installation', period: 'Jun 18-Jul 6 measured days', minimum: '560 piles/day', above: 0, below: 10, latest: 'Jul 6 field: 307 piles + 1 inverter pile', note: 'July 6 field report: United 307 piles plus 1 inverter pile, Latnovva zero, ECCS no work. Official cumulative installed production is 17,701 as of the July 6 workbook.', daily: [{ day: 'Jun 18', value: 20, target: 560, unit: 'piles' }, { day: 'Jun 19', value: 79, target: 560, unit: 'piles' }, { day: 'Jun 22', value: 251, target: 560, unit: 'piles' }, { day: 'Jun 23', value: 101, target: 560, unit: 'piles' }, { day: 'Jun 25', value: 370, target: 560, unit: 'piles' }, { day: 'Jun 26', value: 340, target: 560, unit: 'piles' }, { day: 'Jun 29', value: 261, target: 560, unit: 'piles' }, { day: 'Jun 30', value: 234, target: 560, unit: 'piles' }, { day: 'Jul 1', value: 270, target: 560, unit: 'piles' }, { day: 'Jul 6', value: 307, target: 560, unit: 'piles' }] },
      { task: 'Tracker production control (incl. purlin completion)', period: 'Jun 17-Jul 1', minimum: '48 tracker units/day', above: 4, below: 9, latest: 'Jul 1: 51 tracker/damper units', note: 'Purlin installation is integrated into this tracker control metric: a tracker row is only counted complete once its purlins are installed. Complete tracker cumulative count is 213, pre-assembled rows are 493, and the latest dated activity row shows 51 units on July 1.', daily: [{ day: 'Jun 17', value: 15, target: 48, unit: 'units' }, { day: 'Jun 18', value: 35, target: 48, unit: 'units' }, { day: 'Jun 19', value: 26, target: 48, unit: 'units' }, { day: 'Jun 20', value: 31, target: 48, unit: 'units' }, { day: 'Jun 21', value: 0, target: 48, unit: 'units' }, { day: 'Jun 22', value: 48, target: 48, unit: 'units' }, { day: 'Jun 23', value: 31, target: 48, unit: 'units' }, { day: 'Jun 24', value: 0, target: 48, unit: 'units' }, { day: 'Jun 25', value: 57, target: 48, unit: 'units' }, { day: 'Jun 26', value: 26, target: 48, unit: 'units' }, { day: 'Jun 29', value: 29, target: 48, unit: 'units' }, { day: 'Jun 30', value: 30, target: 48, unit: 'units' }, { day: 'Jul 1', value: 51, target: 48, unit: 'units' }] },
      { task: 'Module installation', period: 'Jul 3-Jul 6 field start', minimum: '5,531 modules/day', above: 0, below: 2, latest: 'Jul 6: 780 modules field-reported', note: 'Workforce field note reports module installation progress. This remains below the full acceleration rate and pending workbook incorporation.', daily: [{ day: 'Jul 3', value: 234, target: 5531, unit: 'modules' }, { day: 'Jul 6', value: 780, target: 5531, unit: 'modules' }] },
      { task: 'ITS MV plowing', period: 'Jun 17-Jul 6', minimum: '1 completed segment/day', above: 6, below: 11, latest: 'Jul 6: 16 cumulative segments complete', note: 'The July 6 ITS workbook confirms plowing at 16 of 46 segments and 43,128 ft installed.', daily: [{ day: 'Jun 17', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 18', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 19', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 20', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 21', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 22', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 23', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 24', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 25', value: 3, target: 1, unit: 'seg' }, { day: 'Jun 26', value: 4, target: 1, unit: 'seg' }, { day: 'Jun 27', value: 1, target: 1, unit: 'seg' }, { day: 'Jun 28', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 29', value: 2, target: 1, unit: 'seg' }, { day: 'Jun 30', value: 5, target: 1, unit: 'seg' }, { day: 'Jul 1', value: 0, target: 1, unit: 'seg' }, { day: 'Jul 2', value: 1, target: 1, unit: 'seg' }, { day: 'Jul 6', value: 0, target: 1, unit: 'seg' }] }
    ],
    successors: [
      { activity: 'Tracker structural assembly', dependency: 'Completed piles by zone/block; final tracker finish after final pile finish', impact: 'Can overlap piling only in released areas. Final tracker structure cannot finish before the revised late-July pile forecast; the August 19 tracker forecast remains provisional and requires 40 completed rows/day.', mitigation: 'Prioritize tracker crews into released workfronts and maintain linked finish-to-finish controls.' },
      { activity: 'Tracker completion including purlins', dependency: 'Completed tracker structure plus both Purlin types confirmed on site', impact: 'The June 17 Purlin load alone cannot complete tracker rows. The first defensible completion wave is after the first Tracker Purlin delivery planned June 23, subject to complete kits and confirmed receipt.', mitigation: 'Confirm each planned load before release, prioritize complete material kits by block, and control daily output through completed tracker rows.' },
      { activity: 'Module installation', dependency: 'Completed tracker rows with both Purlin types installed; final module finish after final purlin finish', impact: 'The earliest defensible first module wave is after June 23, once both Purlin types are physically received and installed on released rows. Final project module completion cannot precede the July 16 planned final Tracker Purlin delivery and subsequent installation.', mitigation: 'Mobilize a controlled module crew only against fully released rows and maintain a block-level tracker/purlin/module constraint log.' },
      { activity: 'DC string wiring / combiner work', dependency: 'Modules set and accessible rows', impact: 'Electrical DC production will be fragmented by workfront availability, increasing crew moves and testing discontinuity.', mitigation: 'Sequence electrical crews by completed inverter block; use partial completion packages and clean turnover boundaries.' },
      { activity: 'Commissioning and MC', dependency: 'Continuous mechanical completion by zone', impact: 'Unconfirmed post receipts and the incomplete purlin plan consume remaining float and make Sep 25 MC more difficult unless early material waves are converted immediately into finished tracker/module work.', mitigation: 'Lock GameChange delivery dates, obtain a site date for the 13,467 unscheduled Purlins, prepare weekend/OT acceleration, and track daily pile burn versus confirmed receipts.' }
    ],
    schedule: [
      { activity: 'D&F Pre-Drilling', contractor: 'Kalamazoo Excavating', start: '2026-05-06', end: '2026-06-30', status: 'Complete', note: 'The June 30 Construction Management PROGRESS sheet shows 7,694 of 7,694 drill-and-backfill units complete.' },
      { activity: 'Current pile delivery burn', contractor: 'ECCS / LATNOVVA / United', start: '2026-06-16', end: '2026-07-06', status: 'Watch', note: 'The refreshed official workbook reports 17,701 installed and 25,509 delivered piles, leaving a 7,808-pile buffer, about 13.9 days at the 560/day acceleration capacity.' },
      { activity: 'June 23 recorded delivery wave', contractor: 'GameChange / Logistics', start: '2026-06-23', end: '2026-06-23', status: 'Confirmed', note: 'The refreshed official workbook records 658 additional delivered piles and receipt lines for 21,672 tracker purlins, 20,251 purlin strips, 640 row tubes, and 2,760 heavy squeeze splices.' },
      { activity: 'June 24 scheduled delivery wave', contractor: 'GameChange / Logistics', start: '2026-06-24', end: '2026-06-24', status: 'Critical', note: 'Shreeya scheduled 6 trucks: 90 Light Green posts, 7,956 tracker purlins, 5,520 heavy splices, 7,840 saddle brackets, and 272 row tubes. Count as pending until POD/site receipt.' },
      { activity: 'June 30 confirmed delivery sequence', contractor: 'GameChange / NTG / Landstar', start: '2026-06-30', end: '2026-06-30', status: 'Critical', note: 'Shreeya confirmed 12 timed loads for June 30 from 7:00 am to 2:30 pm. MRSU8536763 is a carryover from June 29 after late loading in Los Angeles. Count as scheduled/confirmed until POD/site receipt is logged.' },
      { activity: 'July 2 confirmed delivery sequence', contractor: 'GameChange / NTG / Landstar', start: '2026-07-02', end: '2026-07-02', status: 'Critical', note: 'Shreeya confirmed 9 named loads for July 2. Count as scheduled until POD/site receipt, material type, and actual quantities are logged.' },
      { activity: 'July 3 confirmed delivery sequence', contractor: 'GameChange / NTG', start: '2026-07-03', end: '2026-07-03', status: 'Critical', note: 'Shreeya confirmed 6 named NTG loads for July 3: TCLU1477450, YMMU6239469, EITU9400207, TXGU6059112, TRHU8675801, and TRHU6565282. The email shows a blank 10:45 appointment line; confirm whether it was used.' },
      { activity: 'July 7 confirmed delivery sequence', contractor: 'GameChange / NTG / Landstar', start: '2026-07-07', end: '2026-07-07', status: 'Critical', note: 'Shreeya confirmed 11 timed loads for July 7: PL-3295-053-HT, PL-3295-001-RE-PE, EGSU1103910, TEMU8513957, BEAU4969180, YMMU6191811, MSDU5016566, SEGU4551269, PL-3295-022-RE-HA, PL-3295-019-RE-HA, and PL-3295-023-RE-HA. Count as scheduled until POD/site receipt is logged.' },
      { activity: 'Delivery receiving-cap control', contractor: 'GameChange / Greensol Logistics', start: '2026-06-23', end: '2026-07-07', status: 'Critical', note: "Manuel's latest delivery position allows up to 14 pile loads/day plus 8 racking loads/day after the July 3 and July 6 piles-only priority, still subject to appointment discipline and POD/site receipt." },
      { activity: 'United Zone F mobilization and pile-spot marking', contractor: 'United', start: '2026-06-15', end: '2026-06-21', status: 'Mobilizing', note: 'United replaces JB Solar for Zone F. Complete pile-spot marking, crew and equipment mobilization, safety onboarding, access readiness, and workfront release before ramming.' },
      { activity: 'United Zone F pile ramming start', contractor: 'United', start: '2026-06-22', end: '2026-06-22', status: 'Critical', note: 'United starts pile ramming on June 22, subject to the delayed pile delivery, completed marking, access, and released workfronts.' },
      { activity: 'Overall pile installation acceleration', contractor: 'All pile contractors', start: '2026-06-22', end: '2026-07-28', status: 'Critical', note: 'The official workbook leaves 13,651 piles. July 6 field output was 307 piles plus 1 inverter pile versus the 560/day target; output remains constrained by Area F hard soil and rig availability.' },
      { activity: 'Tracker Structural Assembly', contractor: 'ECCS', start: '2026-06-08', end: '2026-08-19 provisional', status: 'At Risk', note: 'Official cumulative counts remain 213 complete trackers and 493 pre-assembled rows (Jul 6 workbook). Daniel Morilla reported no tracker progress on July 6 and planned Area A4 release next.' },
      { activity: 'ITS HDD boring', contractor: 'ITS', start: '2026-06-12', end: '2026-08-15', status: 'Active', note: 'Ten of 20 bores are complete with 3,554.2 ft installed through the July 6 ITS workbook. July 6 daily log shows 0 ft boring.' },
      { activity: 'ITS MV cable plowing', contractor: 'ITS', start: '2026-06-25', end: '2026-08-15', status: 'Active', note: 'July 6 ITS workbook confirms 16 of 46 plow segments complete and 43,128 ft installed; July 6 daily log shows 0 ft plowing.' },
      { activity: 'Control building foundation and delivery gate', contractor: 'AB Power / SET team', start: '2026-06-20', end: '2026-07-10', status: 'Critical', note: 'July 6 SET tracker still shows 8.7% overall progress. Control-building delivery remains tracked to the July 7 committed date and July 10 required-on-site gate.' },
      { activity: 'SET equipment required-on-site gate', contractor: 'SET team / Procurement / Suppliers', start: '2026-06-24', end: '2026-07-10', status: 'Critical', note: 'July 6 SET supply tracker still shows transformer and control building in fabrication; several electrical items remain committed after the July 10 required-on-site gate and require procurement acceleration.' },
      { activity: 'Inverter foundation readiness', contractor: 'EPC / Civil / Electrical', start: '2026-06-20', end: '2026-07-25 provisional', status: 'Critical', note: 'The 23 inverter units are expected to land at the end of July, not the beginning of July. All inverter pile foundations must be ready before the first inverter arrives.' },
      { activity: 'Inverter Installation', contractor: 'EPC / OEM', start: '2026-07-27', end: '2026-09-15', status: 'Confirmed', note: '23 x 4.2 MW units. Installation is separated from the SET/control-building scope and depends on completed inverter pile foundations before first delivery.' },
      { activity: 'Purlin and racking delivery sequence', contractor: 'GameChange / Logistics', start: '2026-06-17', end: '2026-07-16', status: 'Critical', note: 'The June 23 workbook records 21,672 tracker purlins plus purlin strips, row tubes, and splices. Remaining rolling deliveries continue through the July 16 final planned tracker-purlin date; complete kits require receipt and block allocation.' },
      { activity: 'Workforce module crew mobilization', contractor: 'Workforce', start: '2026-06-29', end: '2026-07-06', status: 'Critical', note: 'Workforce is expected to land June 29 with approximately 22 workers. Use this as mobilization/ramp only; module erection starts only against purlin-complete, QA-released rows.' },
      { activity: 'Tracker completion including purlins', contractor: 'GameChange / ECCS', start: '2026-06-23', end: '2026-09-18', status: 'Critical', note: 'Purlin work is controlled inside the completed tracker-row metric from July 3 forward. June 23 receipts must be allocated into complete block kits and released workfronts.' },
      { activity: 'Final module installation completion', contractor: 'Workforce', start: '2026-07-03', end: '2026-10-09', status: 'Critical', note: 'Workforce field note reports 780 modules on July 6, pending official workbook incorporation. The activity has started, but full-field production still depends on released tracker rows and the module crew ramp.' },
      { activity: 'DC Wire / LV Installation', contractor: 'East Carolina + Self-Perform', start: '2026-07-07', end: '2026-10-12 provisional', status: 'Critical', note: 'The LV scope will use an aerial messenger-wire-supported harness / BLA-style installation from tracker rows to the junction boxes. First Chemik pre-tailored cable reels are expected July 7, and East Carolina plus self-perform crews should start the pull, support, and terminations immediately behind released module workfronts by block.' },
      { activity: 'Electrical Pre-Commissioning', contractor: 'EPC + OEMs', start: '2026-09-15', end: '2026-11-01', status: 'Planned', note: 'Zonal energization after inverter, MV/HDD, tracker, module, and DC/LV turnover by block.' }
    ],
    fieldResourceSnapshots: [
      { label: 'Jun 17 actual', week: 'W25', people: 136, color: '#b53030', offset: -18 },
      { label: 'Jun 30 official', week: 'W27', people: 148, color: '#2769a8', offset: 18 },
      { label: 'Jul 6 field', week: 'W28', people: 70, color: '#168a5b', offset: 48 }
    ],
    actualResources: [
      { contractor: 'ECCS', people: 0, label: 'No work Jul 6' },
      { contractor: 'United', people: 22, label: '22 people / 7 rigs' },
      { contractor: 'Latnovva', people: 17, label: '17 people' },
      { contractor: 'ITS', people: 14, label: '14 crew' },
      { contractor: 'Workforce', people: 17, label: '17 people' }
    ],
    resourcePlan: [
      { label: 'Total site resources', actual: 148, target: 105, targetLabel: 'Acceleration peak 95-105', note: 'Includes field labor plus management/QC/HSE; actual is the June 30 official manpower table from the Jul 1 Delivery/Mechanical workbook.' },
      { label: 'Tracker / purlin crew', actual: 47, target: 45, targetLabel: '38 avg / 40-45 peak', note: 'ECCS visible field resources are compared with the tracker/purlin acceleration target.' },
      { label: 'Module crew Phase 1', actual: 0, committed: 22, target: 22, targetLabel: '22 by Jul 7', note: 'Workforce is expected to land June 29 with about 22 workers for the rolling start.' },
      { label: 'Module full-field crew', actual: 0, committed: 22, target: 40, targetLabel: '40 by Jul 13+', note: 'Phase 2 reinforcement adds 18 workers to reach the full-field module gate.' },
      { label: 'Greensol site team', actual: 24, target: 24, targetLabel: '15 staff + 9 labor', note: 'User-provided fixed Greensol site staffing basis.' }
    ],
    mechanicalManpowerLoad: [
      { week: 'Jun 22', pile: 9, tracker: 16, module: 0, management: 13, total: 38 },
      { week: 'Jun 29', pile: 10, tracker: 28, module: 0, management: 13, total: 51 },
      { week: 'Jul 6', pile: 10, tracker: 35, module: 0, management: 13, total: 58 },
      { week: 'Jul 13', pile: 10, tracker: 42, module: 22, management: 13, total: 87 },
      { week: 'Jul 20', pile: 10, tracker: 50, module: 37, management: 13, total: 110 },
      { week: 'Jul 27', pile: 10, tracker: 42, module: 40, management: 13, total: 105 },
      { week: 'Aug 3', pile: 0, tracker: 42, module: 40, management: 13, total: 95 },
      { week: 'Aug 10', pile: 0, tracker: 42, module: 40, management: 13, total: 95 },
      { week: 'Aug 17', pile: 0, tracker: 42, module: 40, management: 13, total: 95 },
      { week: 'Aug 24', pile: 0, tracker: 42, module: 40, management: 13, total: 95 },
      { week: 'Sep 7', pile: 0, tracker: 42, module: 40, management: 13, total: 95 },
      { week: 'Sep 14', pile: 0, tracker: 42, module: 40, management: 13, total: 95 },
      { week: 'Sep 21', pile: 0, tracker: 0, module: 40, management: 10, total: 50 },
      { week: 'Sep 28', pile: 0, tracker: 0, module: 40, management: 10, total: 50 },
      { week: 'Oct 5', pile: 0, tracker: 0, module: 0, management: 5, total: 5 }
    ],
    mechanicalManpowerMilestones: [
      { week: 'Jun 22', label: 'Acceleration plan starts', color: '#b53030', row: 0 },
      { week: 'Jul 27', label: 'Piles complete · Jul 28', color: '#66716d', row: 1 },
      { week: 'Sep 14', label: 'Trackers / purlins · Sep 18', color: '#168a5b', row: 0 },
      { week: 'Oct 5', label: 'Modules · Oct 9', color: '#2769a8', row: 1 }
    ],
    personnelOutlook: [
      { week: 'W22', date: 'May 25', people: 135 },
      { week: 'W23', date: 'Jun 1', people: 281 },
      { week: 'W24', date: 'Jun 8', people: 281 },
      { week: 'W25', date: 'Jun 15', people: 281 },
      { week: 'W26', date: 'Jun 22', people: 229 },
      { week: 'W27', date: 'Jun 29', people: 228 },
      { week: 'W28', date: 'Jul 6', people: 228 },
      { week: 'W29', date: 'Jul 13', people: 228 },
      { week: 'W30', date: 'Jul 20', people: 310 },
      { week: 'W31', date: 'Jul 27', people: 220 },
      { week: 'W32', date: 'Aug 3', people: 255 },
      { week: 'W33', date: 'Aug 10', people: 255 },
      { week: 'W34', date: 'Aug 17', people: 205 },
      { week: 'W35', date: 'Aug 24', people: 205 },
      { week: 'W36', date: 'Aug 31', people: 205 },
      { week: 'W37', date: 'Sep 7', people: 205 },
      { week: 'W38', date: 'Sep 14', people: 205 },
      { week: 'W39', date: 'Sep 21', people: 155 },
      { week: 'W40', date: 'Sep 28', people: 155 },
      { week: 'W41', date: 'Oct 5', people: 130 },
      { week: 'W42', date: 'Oct 12', people: 130 },
      { week: 'W43', date: 'Oct 19', people: 75 },
      { week: 'W44', date: 'Oct 26', people: 75 },
      { week: 'W45', date: 'Nov 2', people: 75 },
      { week: 'W46', date: 'Nov 9', people: 75 },
      { week: 'W47', date: 'Nov 16', people: 0 }
    ],
    milestones: [
      { name: 'Mechanical Completion', target: 'Sep 25, 2026', forecast: 'Oct 10-15, 2026 provisional', status: 'Critical', note: 'The revised late-July pile and provisional August 19 tracker forecasts leave no acceleration margin; MC still depends on full purlin completion by September 18 and modules by October 9.' },
      { name: 'Provisional Interconnection', target: 'Oct 16, 2026', forecast: 'Oct 20-25, 2026', status: 'Critical', note: 'Depends on revised MC; utility/offtake renegotiation likely required.' },
      { name: 'Commercial Operation Date', target: 'Nov 9, 2026', forecast: 'Nov 5-9, 2026', status: 'High', note: 'Feasible only in optimistic scenario; zero float remains.' },
      { name: 'Substantial Completion', target: 'Nov 30, 2026', forecast: 'Nov 30, 2026', status: 'Watch', note: 'Still achievable if COD is protected and outdoor work closes before weather stop.' }
    ],
    risks: [
      { title: 'Pile delivery buffer improved, but July 7 loads still need POD confirmation', level: 'Watch', owner: 'GameChange / Shreeya Devkota / Karina Mucino / Manuel Ramirez / Audelio Zuniga', note: 'The refreshed workbook shows 7,808 piles available above installed production, about 13.9 days at the 560-pile/day acceleration capacity. Shreeya confirmed 11 named loads for July 7; treat them as scheduled until POD/site receipt, material type, and actual quantities are confirmed.' },
      { title: 'Area F hard soil is still limiting pile output', level: 'Critical', owner: 'Audelio Zuniga / United / Manuel Ramirez', note: 'July 6 WhatsApp field notes show United at 307 piles plus 1 inverter pile with 7 ramming machines, still below the 560/day target. Hard soil in Area F continues to require stronger machines, additional rigs, or pre-drilling support to protect the July 28 pile gate.' },
      { title: 'Complete tracker rows control module release', level: 'Critical', owner: 'GameChange / ECCS / Manuel Ramirez', note: 'Purlins are controlled inside completed tracker rows, not as a separate daily log. Workforce reported 780 modules on July 6, but module production still needs fully complete, QA-cleared tracker rows; Daniel reported no tracker progress and Area A4 release planned next.' },
      { title: 'SET foundation, delivery dates, and equipment commitments all need closure', level: 'Critical', owner: 'Axel Cano / AB Power / Karina Mucino / Joshua Spalding / Project Management', note: 'July 6 SET tracker shows 8.7% overall progress. Control-building delivery remains tracked to the July 7 committed date and July 10 required-on-site gate. Transformer, control building, and structural steel remain in fabrication, and several electrical items show committed dates after the July 10 required-on-site gate.' },
      { title: 'ITS plowing must sustain weekly progress', level: 'Watch', owner: 'ITS / Audelio Zuniga / Angel Urbina', note: 'July 6 ITS workbook confirms 16 of 46 plow segments complete and 43,128 ft plowed, but the July 6 daily log shows 0 ft for both plowing and boring. Keep daily LF and segment reporting active while closing the remaining 10 bores.' },
      { title: 'Area G civil release must convert into workfront access', level: 'Critical', owner: 'Rosario Ruiz / Audelio Zuniga / Lounsbury', note: 'Rosario Ruiz Week 26 email says Area G is released for pile driving and material distribution. Civil cut/fill in Area G starts after basin completion; this needs to convert quickly into mechanical access.' }
    ]
  };
