'use strict';
// Murch dashboard data - update THIS file for daily changes
// CACHE BUSTER: Jul 24, 2026 (Fri) [rev c: MAIN TRANSFORMER SET + Workforce tracker lines + QC rebase] — Jul 23: piles +284 (United 30 motor F + 192 G + ECCS 62 E; +15 CB/TP electrical outside scope), trackers +28, modules +3,456 (Brumont 2,000 + Workforce 1,456). Jul 24: trackers +30 (ECCS E), modules +3,134 (Workforce 1,730 + Brumont 1,404), no pile production reported. Basis: piles 25,959 (82.8%, req 1,798/day to Jul 28 — finish projects ~Aug 7); trackers 851 (34.2%, req 53/day); modules 30,780 (18.0%, req 3,803/day). SET 20.0%, piers 6/17. All 9 GameChange tube trucks landed Fri Jul 24; 16 purple tubes remain (Wed Jul 29).
// Note: assetVersion, assetBase, asset(), and assetFallback() are defined in index.html's inline script
// Duplicate declarations have been removed to fix SyntaxError: Identifier 'assetVersion' has already been declared
window.MURCH_DATA = {
    control: {
      asOf: 'Jul 24, 2026',
      piles:    { installed: 25959, total: 31352, gate: '2026-07-28', gateLabel: 'Jul 28', required: 1798, capacity: null, name: 'Piles', unit: 'piles/day' },
      trackers: { installed: 851, released: 235, total: 2486, gate: '2026-08-30', gateLabel: 'Aug 30', required: 53, capacity: 48, name: 'Trackers incl. purlins', unit: 'rows/day' },
      modules:  { installed: 30780, total: 171470, gate: '2026-09-06', gateLabel: 'Sep 6', required: 3803, capacity: null, name: 'Modules', unit: 'mod/day' },
      electrical: { installed: 0, total: 274720, gate: '2026-09-18', gateLabel: 'Sep 18', required: 5723, capacity: null, name: 'LV Electrical', unit: 'lf/day' },
      mc:       { target: 'Sep 25', forecast: 'Sep 20-25', name: 'Mechanical Completion' }
    },
    manpowerHistory: [
      { day: 'Jun 17', total: 136, src: 'field actual' },
      { day: 'Jun 25', total: 149, src: 'workbook' },
      { day: 'Jun 26', total: 134, src: 'workbook' },
      { day: 'Jun 29', total: 146, src: 'workbook' },
      { day: 'Jun 30', total: 148, src: 'official' },
      { day: 'Jul 7', total: 170, src: 'field report' },
      { day: 'Jul 9', total: 191, src: 'site board' },
      { day: 'Jul 13', total: 191, src: 'field snapshot' },
      { day: 'Jul 14', total: 202, src: 'site board' },
      { day: 'Jul 15', total: 209, src: 'site board' },
      { day: 'Jul 16', total: 198, src: 'site board' },
      { day: 'Jul 20', total: 192, src: 'site board' }
    ],
    manpowerMixToday: { day: 'Jul 20, 2026', total: 192, mix: [
      { trade: 'Trackers & Piling', people: 97, color: '#0c5f43' },
      { trade: 'Module Installation', people: 51, color: '#168a5b' },
      { trade: 'Electrical & SET', people: 14, color: '#2769a8' },
      { trade: 'Civil & Fencing', people: 11, color: '#b96f18' },
      { trade: 'GreenSol EPC', people: 19, color: '#66716d' }
    ] },
    contractorScore: [
      { date: 'Jul 24 Fri', contractor: 'Workforce', trade: 'Trackers', output: 0, resource: '15-person racking crew — dampers & actuators installed on mounted trackers (final completion components)', perUnit: 0, criterion: 53, critLabel: 'Finishing work: dampers/actuators are the last components before a row can close incl. purlins — no full rows closed Jul 24; the Jul 23 EW rows advance toward completion' },
      { date: 'Jul 24 Fri', contractor: 'ECCS', trade: 'Trackers', output: 30, resource: '53 people · zone E', perUnit: 30, criterion: 53, critLabel: '53 rows/day now required — 30 in Zone E; best back-to-back tracker days since Jul 14 (28 + 30)' },
      { date: 'Jul 24 Fri', contractor: 'Workforce', trade: 'Modules', output: 1730, resource: '16 people modules (zone C) + 15 people racking (dampers & actuators on erected trackers)', perUnit: 1730, criterion: 2000, critLabel: '2,000 mod/day target — 1,730; racking crew on dampers/actuators, no new rows' },
      { date: 'Jul 24 Fri', contractor: 'Brumont', trade: 'Modules', output: 1404, resource: '14 people · zone C — lost 4 people vs Jul 23', perUnit: 1404, criterion: 2000, critLabel: '2,000 mod/day target — 1,404; crew shrank from 18 to 14, output followed' },
      { date: 'Jul 24 Fri', contractor: 'United', trade: 'Piles', output: 0, resource: 'No daily production log posted for Jul 24', perUnit: 0, criterion: 80, critLabel: 'NO PILE REPORT Jul 24 — zero piles logged project-wide; chase the United/Latnovva daily logs' },
      { date: 'Jul 23 Thu', contractor: 'United', trade: 'Piles', output: 222, resource: '27 people · 6 rigs (2 damaged) — 192 Zone G + 30 motor F; plus 5 CB + 10 TP electrical; refusal-pile reinstall + tap-downs', perUnit: 56, criterion: 80, critLabel: '80 piles/rig-day — 56/rig on 4 running rigs; Zone G ramp is real (192)' },
      { date: 'Jul 23 Thu', contractor: 'Workforce', trade: 'Trackers', output: 9, resource: '14-person racking crew — 17 tracker rows advanced to 50% in Zone EW (~8.5 row-equivalents)', perUnit: 9, criterion: 51, critLabel: '17 rows at 50% (EW) ≈ 9 row-equivalents produced — counted into the completed cumulative only when the rows close incl. purlins' },
      { date: 'Jul 23 Thu', contractor: 'ECCS', trade: 'Trackers', output: 28, resource: '54 people · 28 trackers + 62 tracker piles zone E', perUnit: 28, criterion: 51, critLabel: '51 rows/day — 28 in Zone E plus 62 piles; dual-front day' },
      { date: 'Jul 23 Thu', contractor: 'Brumont', trade: 'Modules', output: 2000, resource: '18 people · zone C', perUnit: 2000, criterion: 2000, critLabel: '2,000 mod/day target — ON target for the 2nd straight day' },
      { date: 'Jul 23 Thu', contractor: 'Workforce', trade: 'Modules', output: 1456, resource: '15 people modules (zone C) + 14 people racking (17 rows at 50%, zone EW)', perUnit: 1456, criterion: 2000, critLabel: '2,000 mod/day target — 1,456; combined day 3,456 modules, best since Jul 20' },
      { date: 'Jul 22 Wed', contractor: 'Brumont', trade: 'Modules', output: 2055, resource: '18 people · zone C', perUnit: 2055, criterion: 2000, critLabel: '2,000 mod/day target — 2,055, ABOVE target; first sub to clear it' },
      { date: 'Jul 22 Wed', contractor: 'ECCS', trade: 'Trackers', output: 39, resource: '54 people · 39 trackers zone C + 35 tracker piles E + 20 CB piles + 1 inverter foundation zone G', perUnit: 39, criterion: 51, critLabel: '51 rows/day — 39 in the released Zone C front; best tracker day since Jul 14' },
      { date: 'Jul 22 Wed', contractor: 'United', trade: 'Piles', output: 167, resource: '27 people · 7 rigs (1 damaged) — 104 motor piles F + 63 G; plus 5 CB + 60 TP electrical', perUnit: 28, criterion: 80, critLabel: '80 piles/rig-day — 28/rig; heavy electrical-pile share (65) and dispersed F remainder' },
      { date: 'Jul 22 Wed', contractor: 'Workforce', trade: 'Modules', output: 832, resource: '15 people modules (zone A) + 15 people racking (11 rows pre-assembled zone EW)', perUnit: 832, criterion: 2000, critLabel: '2,000 mod/day target — crew split with the EW racking front; combined day 2,887 modules' },
      { date: 'Jul 22 Wed', contractor: 'LATNOVVA', trade: 'Piles', output: 0, resource: '12 people · 1 rig — tension-pile CORRECTION work zone A (rework, no new production)', perUnit: 0, criterion: 80, critLabel: '80 piles/rig-day — day spent on electrical tension-pile corrections in zone A' }
    ],
    scope: [
      { title: 'EPC Management', metric: 'Turnkey', note: 'Project management, safety, QC, contractor deliverables, owner reporting, permitting support, and trade coordination through completion.' },
      { title: 'Civil and Environmental', metric: 'G released', note: 'Rosario Week 26 email says Area G is released for pile driving and material distribution; Area G cut/fill starts after basin completion.' },
      { title: 'Mechanical BOS', metric: '31,352 piles · 2,486 trackers', note: 'Pile driving (25,959 executed, 82.8%), GameChange SAT tracker assembly incl. purlins (851 done, 34.2% — 235 QA-released, 616 pending Quality; released count stale since Jul 20), and module placement (30,780 executed, 18.0%). D&F pre-drilling complete (7,694/7,694).' },
      { title: 'Electrical BOS', metric: 'ITS plowing on site', note: 'MV collection, HDD, plowing, grounding, DC string and combiner wiring, LV/AC works, inverter installation, SCADA, and testing. Joshua Spalding reported the ITS plowing machine arrived on June 19.' },
      { title: 'Procurement', metric: '171,470 modules', note: 'Panels, racking, purlins, actuators, controllers, cables, inverter stations, combiner boxes, and SET equipment.' },
      { title: 'Commissioning', metric: 'PIS Oct 16', note: 'Cold commissioning, energization, tracker testing, inverter start-up, PR test path, punch list, COD, and substantial completion.' }
    ],
    photos: [
      { src: 'https://claped71.github.io/murch-dashboard/assets/recent/thumb-recent-41.jpg?v=20260725-transformer', fallbackSrc: 'https://claped71.github.io/murch-dashboard/assets/recent/recent-41.jpg', date: 'July 24, 2026', title: 'MILESTONE — MAIN POWER TRANSFORMER set on its foundation (Substation)', note: 'Geotagged Jul 24, 15:33 (N 42° 12\' 37", W 86° 0\' 58", Lawrence MI): the main power transformer (Pennsylvania Transformer Technology unit) craned onto its completed foundation inside the containment berm — the equipment the whole energization path was waiting on is ON SITE and SET. Foundation and berm were ready since Jul 12. Remaining controlling SET equipment: breakers and structural steel.' },
      { src: 'https://claped71.github.io/murch-dashboard/assets/recent/thumb-recent-42.jpg?v=20260725-pierAN01F5', fallbackSrc: 'https://claped71.github.io/murch-dashboard/assets/recent/recent-42.jpg', date: 'July 24, 2026', title: 'Substation pier AN01-F5 poured — 6 of 17 piers complete incl. concrete', note: 'Geotagged Jul 24, 18:15 (N 42° 12\' 37", W 86° 0\' 58", Lawrence MI): pier AN01-F5 with concrete poured and the anchor-bolt template set — the pier front that stood at 2 of 17 on Jul 22 reached 6 of 17 by Jul 24 (Dig It under Axel Cano, 3-4 piers/day pace holding). In the background, the main power transformer hangs from the crane during its foundation set — both SET milestones landed the same afternoon.' },
      { src: 'https://claped71.github.io/murch-dashboard/assets/recent/thumb-recent-40.jpg?v=20260722-pierE5', fallbackSrc: 'https://claped71.github.io/murch-dashboard/assets/recent/recent-40.jpg', date: 'July 21, 2026', title: 'MILESTONE — first substation pier under construction: Pier E5 (2 of 17)', note: 'Geotagged Jul 21, 19:06 (N 42° 12\' 36", W 86° 0\' 57", Lawrence MI): the delayed substation pier construction is finally RUNNING. Pier E5 formed with the anchor-bolt cage set — 2 of 17 piers, built by DIG IT (AB Power subcontractor) under Axel Cano (SET Site Manager). Plan: 3-4 more piers formed Jul 22 ; by Jul 23 the first 2 of 17 piers are complete including concrete, at a steady 3-4 piers/day. The SET tracker is at 16.7% overall (civil 52.7%, structural 5.7%, electrical 5.2%).' },
      { src: 'https://claped71.github.io/murch-dashboard/assets/recent/thumb-recent-39.jpg?v=20260721-trailers', fallbackSrc: 'https://claped71.github.io/murch-dashboard/assets/recent/recent-39.jpg', date: 'July 21, 2026', title: 'Office trailers relocated — Zone D released for slab demolition', note: 'Relocation confirmation, Jul 21: the office trailer compound has been moved off its Zone D position to the new laydown. The previously occupied area in Zone D is now RELEASED — demolition of the Zone D concrete slab can proceed, opening the path to the Zone D pile workfront (1,468 piles, 0 installed, material-hold pending).' },
      { src: 'https://claped71.github.io/murch-dashboard/assets/recent/thumb-recent-38.jpg?v=20260718-jb-chemik', fallbackSrc: 'https://claped71.github.io/murch-dashboard/assets/recent/recent-38.jpg', date: 'July 18, 2026', title: '72 LV junction boxes received — Chemik, Zone D', note: 'Saturday Jul 18, 09:54 (geotagged Lawrence, MI): first Chemik LV hardware on site — 72 DC junction/disconnect boxes (DB) received and staged in Zone D. Tracked as received material only; the 419-box mounting scope stays at 0 installed until the boxes are set. Leading edge of the material-gated LV pull that kicks off Jul 21.' },
      { src: 'https://claped71.github.io/murch-dashboard/assets/recent/thumb-recent-34.jpg?v=20260714-jul14-photos', fallbackSrc: 'https://claped71.github.io/murch-dashboard/assets/recent/recent-34.jpg', date: 'July 14, 2026', title: 'Module front vs. bare trackers — Zone A into Zone C', note: 'Jul 14 midday: installed module rows on the far block with erected trackers still bare in the foreground — the module crews are chasing the QA-released tracker workfront after Monday’s record 2,922 modules.' },
      { src: 'https://claped71.github.io/murch-dashboard/assets/recent/thumb-recent-35.jpg?v=20260714-jul14-photos', fallbackSrc: 'https://claped71.github.io/murch-dashboard/assets/recent/recent-35.jpg', date: 'July 14, 2026', title: 'Tracker crew on the row — Zone C', note: 'Crew working a tracker row in Zone C, the controlling front. 793 rows done of 2,486 (235 QA-released); ECCS restarted Monday with 29 rows and must at least double that rate.' },
      { src: 'https://claped71.github.io/murch-dashboard/assets/recent/thumb-recent-36.jpg?v=20260714-jul14-photos', fallbackSrc: 'https://claped71.github.io/murch-dashboard/assets/recent/recent-36.jpg', date: 'July 14, 2026', title: 'Inverter/PCS station set on foundation', note: 'Prefabricated station landed on its foundation inside the fenced yard, with formwork and rebar set for the adjacent pad — 190 of 230 inverter piles complete (82.6%) ahead of the end-July inverter arrivals.' },
      { src: 'https://claped71.github.io/murch-dashboard/assets/recent/thumb-recent-37.jpg?v=20260714-jul14-photos', fallbackSrc: 'https://claped71.github.io/murch-dashboard/assets/recent/recent-37.jpg', date: 'July 14, 2026', title: 'Underground electrical trench alongside erected trackers', note: 'Open trench with conduit installed beside the access road and erected tracker rows, feeding the LV/DC scope that kicked off Jul 14.' },
      { src: 'https://claped71.github.io/murch-dashboard/assets/recent/thumb-recent-33.jpg?v=20260712-berm', fallbackSrc: 'https://claped71.github.io/murch-dashboard/assets/recent/recent-33.jpg', date: 'July 12, 2026', title: 'Transformer-foundation containment berm complete — Substation', note: 'Geotagged Jul 12, 13:24 (Lawrence, MI): substation containment berm and main power transformer foundation complete — ready ahead of the transformer delivery (unit still in fabrication).' },
      { src: 'https://claped71.github.io/murch-dashboard/assets/recent/thumb-recent-30.jpg?v=20260710-jul9-photos', fallbackSrc: 'https://claped71.github.io/murch-dashboard/assets/recent/recent-30.jpg', date: 'July 9, 2026', title: 'Inverter pile ramming — Area E', note: 'Ramming rig driving inverter-station foundation piles in Area E; 12 of 23 stations now have piles complete.' },
      { src: 'https://claped71.github.io/murch-dashboard/assets/recent/thumb-recent-31.jpg?v=20260710-jul9-photos', fallbackSrc: 'https://claped71.github.io/murch-dashboard/assets/recent/recent-31.jpg', date: 'July 9, 2026', title: 'First modules installed — Area A', note: 'Installed module rows in Area A alongside bare trackers awaiting panels; module production hit a record 1,308 on July 9.' },
      { src: 'https://claped71.github.io/murch-dashboard/assets/recent/thumb-recent-32.jpg?v=20260710-jul9-photos', fallbackSrc: 'https://claped71.github.io/murch-dashboard/assets/recent/recent-32.jpg', date: 'July 9, 2026', title: 'Greensol self-perform rework — damper change, Area A', note: 'Greensol personnel replacing tracker dampers in Area A as part of the QA rework program ahead of module release.' },
      { src: 'https://claped71.github.io/murch-dashboard/assets/recent/thumb-recent-28.jpg?v=20260708-cb-install', fallbackSrc: 'https://claped71.github.io/murch-dashboard/assets/recent/recent-28.jpg', date: 'July 7, 2026', title: 'Control building set at substation', note: 'Axel Cano: substation control building delivered and installed on its foundation the night of July 7 — the July 10 required-on-site gate is met.' },
      { src: 'https://claped71.github.io/murch-dashboard/assets/recent/thumb-recent-21.jpg?v=20260708-cb-install', fallbackSrc: 'https://claped71.github.io/murch-dashboard/assets/recent/recent-21.jpg', date: 'June 25, 2026', title: 'Golden Row installation', note: 'Golden Row tracker/racking installation shared by Audelio Zuniga, documenting the first representative mechanical completion sequence ahead of module release.' },
      { src: 'https://claped71.github.io/murch-dashboard/assets/recent/thumb-recent-23.jpg?v=20260708-cb-install', fallbackSrc: 'https://claped71.github.io/murch-dashboard/assets/recent/recent-23.jpg', date: 'June 25, 2026', title: 'ITS MV plowing workfront', note: 'MV cable/plowing workfront activity, supporting the ITS production sequence by installed footage and completed segments.' },
      { src: 'https://claped71.github.io/murch-dashboard/assets/recent/thumb-recent-1.jpg?v=20260708-cb-install', fallbackSrc: 'https://claped71.github.io/murch-dashboard/assets/recent/recent-1.jpg', date: 'June 19, 2026', title: 'ITS plowing machine arrival', note: 'ITS plowing machine staged for the medium-voltage cable scope.' },
      { src: 'https://claped71.github.io/murch-dashboard/assets/recent/thumb-recent-15.jpg?v=20260708-cb-install', fallbackSrc: 'https://claped71.github.io/murch-dashboard/assets/recent/recent-15.jpg', date: 'June 19, 2026', title: 'ITS MV boring operation', note: 'Excavator and crew supporting the ITS medium-voltage boring scope at the wooded crossing workfront.' },
      { src: 'https://claped71.github.io/murch-dashboard/assets/recent/thumb-recent-19.jpg?v=20260708-cb-install', fallbackSrc: 'https://claped71.github.io/murch-dashboard/assets/recent/recent-19.jpg', date: 'June 19, 2026', title: 'SET foundation formwork', note: 'Substation foundation and containment formwork under construction, documenting current SET civil progress.' },
      { src: 'https://claped71.github.io/murch-dashboard/assets/recent/thumb-recent-24.jpg?v=20260708-cb-install', fallbackSrc: 'https://claped71.github.io/murch-dashboard/assets/recent/recent-24.jpg', date: 'June 24, 2026', title: 'Civil/fence workfront conditions', note: 'Field view of civil and fencing workfront conditions supporting Area E/F/G release sequencing.' },
      { src: 'https://claped71.github.io/murch-dashboard/assets/recent/thumb-recent-14.jpg?v=20260708-cb-install', fallbackSrc: 'https://claped71.github.io/murch-dashboard/assets/recent/recent-14.jpg', date: 'June 19, 2026', title: 'Racking workfront beside access road', note: 'Installed pile and racking lines beside stabilized access, documenting active mechanical workfront conditions.' },
      { src: 'https://claped71.github.io/murch-dashboard/assets/recent/thumb-recent-26.jpg?v=20260708-cb-install', fallbackSrc: 'https://claped71.github.io/murch-dashboard/assets/recent/recent-26.jpg', date: 'July 1, 2026', title: 'Control-building access platform fabrication', note: 'Factory photo of access platform/stair components for the control-building package.' }
    ],
    weeklyPlan: [
      { area: '<u>Tracker assembly and QA release — Zones C1/C2 / A / F</u><span style="background:#b53030;color:#fff;padding:1px 6px;border-radius:3px;font-size:10px;font-weight:700;margin-left:6px">CRITICAL</span>',
        target: 'THE controlling front for the week — it sets the ceiling on the module crews. 851 rows done (235 QA-released, 616 pending Quality — released count stale since Jul 20) of 2,486 (34.2%). BREAKTHROUGH: Daniel Morilla confirmed Monday Jul 20 that Zones C1 and C2 release for trackers today with the Client — the first QA releases since Jul 10. Convert the 616-row pending backlog into released workfront this week and keep assembling; releases, not assembly, still govern the module ramp — the module crews are already installing ahead of the formally released count.',
        minimum: '>= 53 completed rows/day to hold Aug 30 (1,635 rows over 31 working days, Mon-Sat). Three assembly fronts now: ECCS ran 28 + 30 completed rows Jul 23-24 (barely half the floor), Workforce racking advanced 17 EW rows to 50% and is closing them with dampers/actuators, and the United racking crew is staffing up (~1.5 wks to full rate). Completed-row credit lands when rows close incl. purlins. QA is the real floor: clear the 616-row pending backlog now that C1/C2 are unlocked.',
        gate: 'QA turnover of finished rows (now unblocking with C1/C2), not the assembly rate. Carry-over: recover the Area F quality documents for zones released internally without the subcontractor paperwork. Field cumulative (851) still reconciling vs the workbook (715 pre-assembled / 311 complete).',
        owners: 'ECCS | Daniel Morilla (QA/QC) | Audelio Zuniga | Manuel Ramirez' },
      { area: '<u>Pile production — rig availability, Zones B / F, open D / G</u><span style="background:#b53030;color:#fff;padding:1px 6px;border-radius:3px;font-size:10px;font-weight:700;margin-left:6px">CRITICAL</span>',
        target: '5,393 piles remain to the Jul 28 gate (25,959 of 31,352 executed, 82.8%). Saturday Jul 18 ran 608 — United 415 (Zone F) + Latnovva 193 (Zone B) — the best per-rig day in a week (104 and 97 per rig), but the Jul 28 gate is unrecoverable at ~560/day fleet capacity and slips to ~early August (~Aug 4-5). Jul 23 ran 284 (United 192 G + 30 F + ECCS 62 E) and Jul 24 logged NO pile production — the finish now projects ~Aug 7 (Jose, Jul 22). Close Zone B (165 left), finish Zone F (429 left) and feed the Zone G ramp (277 done of 3,356).',
        minimum: 'Holding Jul 28 would need ~1,798 piles/day (5,393 over 3 working days) — 3x capacity, unrecoverable. Realistic floor: get every rig running and sustain the fleet maximum daily (~600-700), targeting ~4,000+ piles this week, then re-baseline the pile finish to early August. Saturdays must be worked — Jul 18 trackers and modules were idle.',
        gate: 'Rig repairs are the binding constraint — United on 4 of 6 (2 damaged), Latnovva on 2. Material is not a restriction: 28,343 piles delivered, a 2,384-unit buffer.',
        owners: 'United / LATNOVVA | Audelio Zuniga | Manuel Ramirez | Joshua Spalding' },
      { area: '<u>Module installation ramp — Zones A / C</u><span style="background:#b53030;color:#fff;padding:1px 6px;border-radius:3px;font-size:10px;font-weight:700;margin-left:6px">CRITICAL</span>',
        target: '30,780 of 171,470 executed (18.0%). Jul 23: 3,456 (Brumont 2,000 + Workforce 1,456); Jul 24: 3,134 (Workforce 1,730 + Brumont 1,404 — Brumont lost 4 people). Record 3,601 on Jul 20. Workforce finishes its first 10 MW and takes the next 10 (Luis, Jul 23).',
        minimum: '>= 3,803 modules/day required to hold the Sep 6 finish (140,690 over 37 working days), ramping toward the ~5,500/day full-field rate — the crews have run 2,887-3,456 for four straight days; the last ~700/day comes from Brumont re-manning and Saturdays worked.',
        gate: 'QA-released tracker rows — the C1/C2 release today should widen the ~1.3-day buffer; keep crews only on fully released rows. Golden Row slot-tolerance QC control stays in force.',
        owners: 'Workforce / Brumont | Audelio Zuniga | Daniel Morilla (QA/QC) | Manuel Ramirez' },
      { area: '<u>LV electrical installation — Chemik air-freight gated</u><span style="background:#b53030;color:#fff;padding:1px 6px;border-radius:3px;font-size:10px;font-weight:700;margin-left:6px">CRITICAL</span>',
        target: 'Cable-pull kicked off Tuesday Jul 21 on the first Chemik air deliveries. Total LV pull 274,720 lf (Homerun 229,435 + Chemik trunk 40,313 + harness 4,972), all at 0%. First Chemik hardware landed Jul 18: 72 DC junction/disconnect boxes staged in Zone D (0 of 419 installed). ECCS awarded 11 of 23 inverters; the other 12 pending (decision Wed Jul 22). Start the Chemik trunk on arriving air shipments and stand up the crew.',
        minimum: 'Start Chemik trunk (>= 775 lf/day) on air shipments PL_260601/260709 (ETA Jul 23); ramp homerun (>= ~4,400 lf/day) as cable lands and module blocks release. Finishing the full pull by the Sep 18 DC/LV close now needs ~5,723 lf/day — 21 points of schedule already gone (Jose, Jul 22): START.',
        gate: 'ALL remaining Chemik packages must be AIR-FREIGHTED (project decision Jul 17) and on site before end of August — sea transit cannot meet the milestones. Then released module blocks + ECCS / East Carolina crew size.',
        owners: 'ECCS (11 inv) | East Carolina | Greensol Self-Perform | Luis Romero Montero | Joshua Spalding | Clara Lopez' },
      { area: '<u>GameChange tracker-material deliveries</u>',
        target: 'POSTS COMPLETE (5 loads Mon Jul 20 + 5 Tue Jul 21). NEW CONSTRAINT — RED TORQUE TUBES OUT since Jul 21 (Manuel to GameChange, Jul 22): racking crews skip the rows needing red tubes and return later, slowing assembly. GameChange commits 239 red tubes Fri Jul 24 and a final 97 Sat/Mon (Jul 25/27). Close the open POD (PL-3295-084-HT) and hold GameChange to the no-staging-on-public-roads rule (Road Commission watching).',
        minimum: 'DONE — GameChange moved ALL 9 torque-tube trucks to Fri Jul 24 (avoiding Saturday offload costs); after Friday only 16 purple tubes remain, committed Wed Jul 29. OPEN CLAIM: one purple torque-tube bundle missing from load PL-3295-094-HT (Manuel, Jul 24) — chase the replacement date.',
        gate: 'Red-tube resupply LANDED Fri Jul 24 — tube availability no longer caps assembly; crew ramp does (United racking crew building up, ~1.5 wks to full rate per Manuel). Loads count as scheduled until POD/site receipt.',
        owners: 'GameChange (Shreeya Devkota) | Manuel Ramirez | Karina Mucino' },
      { area: '<u>SET, inverter foundations and inverter arrival</u>',
        target: 'SET at 20.0% overall (civil 59.3%, structural 11.3%, electrical 5.2%); piers 6 of 17 complete (Jul 24). Close the last 4 inverter pile foundations — D10, E12, F16, G20 (190 of 230 piles, 82.6%) — before the end-July arrival of the 23 inverter units. AB Power has presented no work or material-delivery plan; Greensol is pulling partial scope to Michael Power and self-procuring material.',
        minimum: 'All 23 inverter foundations released before first delivery; hold the 3-4 piers/day pace that took SET from 16.7% to 20.0% in three days (piers 2/17 -> 6/17).',
        gate: 'MAIN TRANSFORMER SET ON ITS FOUNDATION Jul 24 (crane set, containment berm ready since Jul 12) — the single biggest energization item is closed. Controlling items now: BREAKERS and structural steel still in fabrication. AB Power work-plan and material-delivery gaps must close.',
        owners: 'AB Power / Michael Power / SET team | Axel Cano | Joshua Spalding | Karina Mucino' },
      { area: '<u>Electrical MV plowing and HDD closeout</u>',
        target: 'ITS is ahead of the electrical sequence: 36 of 46 plow segments complete (120,738 ft) and 17 of 20 MV bores closed (5,162 ft). DC cable-duct bores underway: 2 of 14 COMPLETE (391 LF — DC15HB-04 + DC12HB-08) with DC03HB-02 in progress. A second, larger drill arrived — from Jul 24 two rigs run in parallel: one on DC ducts, one on the MV wetland bores. Close the last 3 MV bores and the remaining 10 plow segments.',
        minimum: '>= 1 plow segment/day and >= 1 completed bore/day with measured-footage reporting once the new drill is running (boring logged 0 ft Jul 13-20 through the frac-out — restore the cadence).',
        gate: 'Crossing approvals, drill/equipment availability and access continuity. EGLE denied swapping the last bores for plowing, so the 4 bores continue as bores.',
        owners: 'ITS | Angel Urbina | Joshua Spalding' },
      { area: '<u>Civil Area G release and internal roads</u>',
        target: 'Finish Area G basins, then start Area G cut/fill — Area G is released for pile driving and material distribution and is the next pile workfront (3,356 piles, 0 installed). Perimeter fence at 95% (only Zone G and gates remain); internal roads at 72%. Rosario Jul 23: cut/fill 100% complete, sediment basins 83%, PS foundations 86%.',
        minimum: 'Daily confirmed grading production in Area G after basin closeout; keep roads easing as the logistics constraint.',
        gate: 'Basin completion controls Area G cut/fill; civil access, gates and drainage must stay ahead of the mechanical fronts.',
        owners: 'Lounsbury / Hurricane / Topland | Rosario Ruiz | Audelio Zuniga' }
    ],
    civilKpis: [
      { title: 'Civil field progress', metric: 'Week 26', note: 'Rosario Ruiz Week 26 email dated July 3 and sent July 6 controls the latest civil workfront note.' },
      { title: 'Area G release', metric: 'Released', note: 'Rosario reports that once Area G basins are finished, cut/fill will start there; Area G is also released for pile driving and material distribution.' },
      { title: 'SET tracker', metric: '20.0% overall', note: 'Jul 24 SET tracker: overall progress 20.0% (civil 59.3%, structural 11.3%, electrical 5.2%) — up from 16.7% on Jul 21; piers 6 of 17 complete. Control building on site since Jul 7. Jul 12 (Sun): transformer-foundation containment berm complete at the substation. Jul 12: all 18 inverter stations available on site have their base plates welded.' }
    ],
    civilActivities: [
      { activity: 'Earthworks cut / fill', company: 'Lounsbury', done: 100, remaining: 0, status: 'Complete', note: 'Rosario Jul 23: Earthworks cut/fill 100% COMPLETE (Lounsbury; Apr 1 – Jul 17). Area G cut/fill starts after the Area G basins are finished.' },
      { activity: 'Perimeter fence', company: 'Hurricane', done: 95, remaining: 5, status: 'On Track', note: 'Rosario Jul 23: G-SET perimeter fence 95% (Hurricane; started Apr 2, end TBD) — Areas A–F 100% complete, only the Zone G remainder and gates left.' },
      { activity: 'Sediment basins / environmental controls', company: 'Lounsbury / ECS', done: 83, remaining: 17, status: 'On Track', note: 'Rosario Jul 23: Sediment basins 83% (Lounsbury; Mar 26 – target Jul 24) — up from 47%. Area G basins must finish before Area G cut/fill starts.' },
      { activity: 'Internal roads', company: 'Topland', done: 72, remaining: 28, status: 'Active', note: 'Rosario Jul 23: Internal roads 72% (Topland; May 26 – target Jul 31) — up from 65.9%. Continued recovery from the 35% Week 24 baseline; roads easing as the logistics constraint.' },
      { activity: 'PS foundations', company: 'United', done: 86, remaining: 14, status: 'Active', note: 'Rosario Jul 23: PS foundations 86% (United; Jun 8 – target Jul 24). Jul 22: 22 of 23 inverter foundations complete, 1 remaining (Jul 17 workbook had 190 of 230 inverter piles). WELDING PROCEDURE received Jul 21 (Daniel Morilla) — clears qualified welding to proceed.' },
      { activity: 'Foundation SET', company: 'AB Power', done: 20.0, remaining: 80.0, status: 'Active', note: 'Jul 24 SET tracker: overall substation progress 20.0% (up from 16.7% on Jul 21); civil 59.3%, structural 11.3%, electrical 5.2%. Containment berm and transformer foundation complete Jul 12. PIERS: 6 of 17 COMPLETE incl. concrete (Jul 24 — 3 added Jul 23, 1 more Jul 24), by Dig It (AB Power sub) under Axel Cano; plan holds 3-4/day. MILESTONE Jul 24: MAIN POWER TRANSFORMER set on its foundation. AB Power SET scope at risk — no work or delivery plan (Jul 17 review); partial scope moving to Michael Power.' }
    ],
    contractors: [
      { name: 'LATNOVVA / assigned areas', scope: 15904, installed: 14195, remaining: 1709, done: 89.3, zones: 'Zones A, B, C, D, EW + shared Area E control (Zone G removed Jul 17)', status: 'Watch', note: "Area-based control allocation only; it is not a new manpower or subcontractor headcount report." },
      { name: 'ECCS / Area E control', scope: 4434, installed: 4258, remaining: 176, done: 96.0, zones: 'Area E shared tracker workfront', status: 'On Track', note: "Area-based control allocation used only so dashboard totals reconcile with Audelio's July 6 official installed-production basis." },
      { name: 'United', scope: 11014, installed: 7506, remaining: 3508, done: 68.1, zones: 'Zones F + G', status: 'Active', note: 'Executed: 7,506 piles — Zone F 7,229 (94.4%) + Zone G 277 (ramping hard: 192 on Jul 23). Jul 23: 222 tracker piles on 6 rigs (2 damaged) plus 5 CB + 10 TP electrical piles; refusal-pile reinstalls and tap-downs continue. NO daily log posted Jul 24. Combined F+G 68.1%. United holds full mechanical (piles + trackers + modules) in F & G; racking crew building up (~1.5 wks to full rate).' },
      { name: 'Project Total', scope: 31352, installed: 25959, remaining: 5393, done: 82.8, zones: "All zones | Construction Manager report", status: 'Critical', note: "Total executed: 25,959 — official block-map 22,900 plus 3,059 field logs not yet mapped. Jul 23 (Thu): 284 tracker piles (United 192 G + 30 motor F + ECCS 62 E) + 15 electrical CB/TP piles outside the 31,352. Jul 24 (Fri): NO pile production reported — no United/Latnovva log posted. Latnovva has not reported since Jul 22 (tension-pile corrections)." }
    ],
    zones: [
      { zone: 'Zone A', contractor: 'Latnovva', scope: 3834, installed: 3834, remaining: 0, done: 100.0, status: 'Complete', note: 'Jul 8 PROGRESS table: Zone A pile installation complete.' },
      { zone: 'Zone C', contractor: 'Latnovva', scope: 2946, installed: 2946, remaining: 0, done: 100.0, status: 'Complete', note: 'July 6 Const. Management workbook; zone complete.' },
      { zone: 'Zone E', contractor: 'ECCS / Latnovva', scope: 8456, installed: 8204, remaining: 252, done: 97.0, status: 'Active', note: 'Jul 23: 8,204 installed (+62 ECCS tracker piles); no Zone E pile report Jul 24.' },
      { zone: 'Zone EW', contractor: 'Latnovva', scope: 846, installed: 846, remaining: 0, done: 100.0, status: 'Complete', note: 'Jul 8 workbook: Zone EW complete at 846 of 846.' },
      { zone: 'Zone B', contractor: 'Latnovva', scope: 2788, installed: 2623, remaining: 165, done: 94.1, status: 'Active', note: 'Executed: 2,623 (94.1%) — through Jul 21 (+84 Tue; 1 of 2 rigs running, 2nd damaged). Block-map still shows 1,457 here; Latnovva self-report leads.' },
      { zone: 'Zone D', contractor: 'TBD / Latnovva', scope: 1468, installed: 0, remaining: 1468, done: 0, status: 'Material Hold', note: '2nd-50% work. Jul 21: office trailers relocated off Zone D — the occupied area is released and demolition of the Zone D concrete slab can proceed ahead of the pile workfront.' },
      { zone: 'Zone F', contractor: 'United', scope: 7658, installed: 7229, remaining: 429, done: 94.4, status: 'Active', note: 'Executed: 7,229 (94.4%) — Jul 23: +30 motor piles (United, 6 rigs, 2 damaged); plus 5 CB + 10 TP electrical piles, outside the 31,352. Refusal-pile reinstalls and tap-downs running.' },
      { zone: 'Zone G', contractor: 'United', scope: 3356, installed: 277, remaining: 3079, done: 8.3, status: 'Active', note: 'STARTED Jul 21 (22); Jul 22: +63; Jul 23: +192 — 277 total, the ramp Manuel predicted is real. FULL Zone G start needs only the SIGNED CHANGE ORDER (ChO) — chase signature. ECCS also completed 1 inverter foundation in Zone G Jul 21. United holds full mechanical in F & G. Area G released for pile driving; cut/fill after basin completion.' }
    ],
    production: [
      { name: 'Project pile installation', remaining: '5,393 piles', target: '~1,798 piles/day required for Jul 28 (560/day stated capacity) — finish projects ~Aug 7', latest: 'Jul 23 (Thu): 284 tracker piles — United 192 (G) + 30 motor (F) + ECCS 62 (E); +15 electrical CB/TP piles outside the 31,352. Jul 24 (Fri): NO pile production reported', cumulative: '25,959 / 31,352 executed (82.8%) — 22,900 official block-map + 3,059 field logs not yet mapped', status: 'Critical', note: 'Executed 25,959 of 31,352 (82.8%). The official block-map roll-up is 22,900; field daily logs add 3,059 piles not yet mapped (mostly Zone B, where Latnovva self-reports lead the block map). Jul 23 (Thu) logged 284 counted tracker piles (United 192 Zone G + 30 motor Zone F on 6 rigs, 2 damaged; ECCS 62 Zone E) against the 1,798/day now required over 3 working days to Jul 28 — the gate projects to ~Aug 7 (Jose, Jul 22). Jul 24 (Fri): NO pile log posted (United/Latnovva) — zero piles recorded; chase the daily logs. Another 15 electrical piles (5 CB, 10 TP) stay outside the 31,352. RECONCILIATION FLAG (Jul 20): Audelio DELIVERY workbook is internally inconsistent on piles — the PROGRESS summary shows 22,900 installed, but his detail tabs (Production Q PILE DRIVING + COMPLETED-by-zone block logs) sum to only 17,678, lagging badly in the active zones (Zone F detail 1,743 vs 5,805 summary; Zone B 500 vs 1,457), and a planning tab shows ~15,550. The field WhatsApp daily logs (25,959) are the controlling production basis; Audelio has been asked to reconcile the summary-vs-detail gap in his file.' },
      { name: 'Pile delivery / site stock', remaining: '3,009 piles undelivered', target: 'Receipts must exceed the 834 piles/day install burn', latest: 'Jul 24 workbook: 28,343 piles delivered (90.4% of 31,352)', cumulative: '28,343 delivered; 2,384 available above the 25,959 executed', status: 'On Track', note: 'Available stock equals delivered piles less executed piles — 2,384 units.  Delivery is no longer the pile-programme constraint.' },
      { name: 'Drill and backfill', remaining: '0 pre-drills', target: 'Scope closed — no gate to piling', latest: 'All units closed in the official workbook', cumulative: '7,694 / 7,694 complete (100.0%)', status: 'Complete', note: 'July 6 Construction Management progress source shows drill-and-backfill complete.' },
      { name: 'Civil grading / cut-fill', remaining: 'Complete', target: '— No approved daily target in source', latest: 'Rosario Jul 23: cut/fill 100% complete (finished Jul 17)', cumulative: '100% complete — Rosario Jul 23 (Lounsbury)', status: 'Complete', note: 'Current percentage follows Rosario Ruiz civil baseline; Week 26 adds Area G release for pile driving and material distribution.' },
      { name: 'Internal roads', remaining: '28% of scope', target: '— No approved daily target in source', latest: 'Rosario Jul 23 civil progress (Topland)', cumulative: '72% complete — target end Jul 31', status: 'Active', note: 'Current percentage follows Rosario Ruiz civil baseline for Areas A-B-C-E; roads continue to control logistics access.' },
      { name: 'Tracker completion incl. purlins', remaining: '1,635 to build · 2,251 to QA-release', target: '53 completed rows/day now required for Aug 30', latest: 'Jul 24 (Fri): 30 completed rows (ECCS, E); Workforce racking on dampers/actuators (final components) · Jul 23 (Thu): 28 completed (ECCS, E) + Workforce 17 rows to 50% in EW (~9 row-equiv, close pending)', note: 'Purlin installation is integrated into this tracker control metric: a row counts once its purlins are installed. Total done is 851 rows — 235 released by Quality and 616 pending QA approval; the released count is STALE since Jul 20 (C1/C2 released with Client that day — updated split owed by Daniel/Jose). NOTE: cumulative under reconciliation — the workbook shows 715 pre-assembled / 311 complete; Maurin walked all rows Jul 14 and Daniel is recounting manually.', cumulative: '851 done (34.2%): 235 QA-released + 616 pending Quality / 2,486 total', status: 'Critical' },
      { name: 'ITS HDD boring', remaining: '3 of 20 MV bores · 12 of 14 DC bores', target: 'Minimum 1 completed bore/day', latest: 'Jul 24: MV boring holds 17 / 20 (85%, 5,162 ft); DC cable-duct bores 2 / 14 COMPLETE (391 LF — DC15HB-04 + DC12HB-08, both Jul 22) with DC03HB-02 in progress; 2nd (larger) drill on site — two rigs from Jul 24: one DC, one MV wetlands', cumulative: '17 / 20 MV bores (85%, 5,162 ft) + 2 / 14 DC bores (391 LF)', status: 'Watch', note: 'Jul 24 ITS control: MV 17 done / 1 in progress / 2 pending; DC 2 done / 1 in progress / 11 pending. Crew 11-12 on Jul 23-24. Jul 17 review: EGLE will not accept swapping the remaining bores for plowing; the last 4 continue, extended ~100 ft each (2x100 ft) to clear the wetland.' },
      { name: 'ITS MV plowing', remaining: '10 of 46 segments', target: 'Minimum 1 completed segment/day', latest: 'Jul 24: plowing holds 36 / 46 (76.6%) — crew concentrated on the DC + wetland bores (two drills running)', cumulative: '36 / 46 segments complete (76.6%); 120,738 ft installed', status: 'On Track', note: 'Jul 20 ITS control: 36 done / 0 in progress / 10 pending. Line status: MV11A 7/10, MV11B 10/12, MV12A 10/13, MV12B 9/11. Plowing comfortably leads the electrical sequence.' },
      { name: 'SET construction', remaining: '80.0% of overall scope', target: '— No approved daily progress target in source', latest: 'Jul 24 SET tracker: overall 20.0% (civil 59.3%, structural 11.3%, electrical 5.2%) — piers 6 of 17 complete incl. concrete', cumulative: '20.0% overall (civil 59.3%, structural 11.3%, electrical 5.2%) per the Jul 24 SET tracker', status: 'Critical', note: 'Overall SET progress from 16.7% (Jul 21) to 20.0% (Jul 24) — pier production holding 3-4/day formed (2/17 Jul 22 -> 5/17 Jul 23 -> 6/17 Jul 24). MILESTONE Jul 24: MAIN POWER TRANSFORMER delivered and SET on its foundation (15:33, crane set). Breakers and structural steel remain in fabrication — now the controlling items for energization. Jul 17 procurement review: AB Power has presented no SET work plan and no material-delivery plan; Greensol is pulling partial scope to a third party (Michael Power) and self-buying missing materials (BUS-connectors urgent). Portico steel structure arriving Jul 16-17; oil-pit grating (tramex) procured separately to close the SET payment milestone and avoid Heelstone objections.' },
      { name: 'Panel delivery', remaining: '14,230 modules to deliver', target: '— No approved daily delivery target in source', latest: '— Latest daily receipt not reported', cumulative: '157,240 / 171,470 delivered (91.7%)', status: 'On Track', note: 'Jul 24 Construction Manager workbook cumulative delivery quantity; 126,460 modules on site above the 30,780 executed.' },
      { name: 'Module installation', remaining: '140,690 modules', target: '3,803 modules/day required for Sep 6 (5,531/day full-field capacity)', latest: 'Jul 24 (Fri): 3,134 modules — Workforce 1,730 + Brumont 1,404 (both zone C; Brumont lost 4 people). Jul 23: 3,456 (Brumont 2,000 + Workforce 1,456)', cumulative: '30,780 modules field-reported, pending official workbook incorporation', status: 'Critical', note: 'Four straight days at 2,887-3,456; Jul 20 remains the record at 3,601. ~3,803/day now required — the ramp is close but not there. Workforce finishes its first 10 MW block and takes the next 10 (Luis, Jul 23). The QA-released tracker split is stale since Jul 20 — updated release count owed. Modules must finish one week after tracker completion: Aug 30 trackers -> Sep 6 module finish.' }
    ],
    dailyProductionHistory: [
      { task: 'Pile installation', period: 'Jun 18-Jul 24 measured days', minimum: '1,798 piles/day (required for Jul 28)', above: 0, below: 28, latest: 'Jul 23 (Thu): 284 — United 192 (G) + 30 motor (F) + ECCS 62 (E). Jul 24 (Fri): NO pile production reported', note: 'Jul 23 logged 284 counted piles; Jul 24 had NO pile log (United/Latnovva) — zero recorded. Far short of the 1,798/day single goal; the finish projects ~Aug 7 (Jose, Jul 22). (560/day is nominal crew capacity, not a target.) Executed 25,959 = official block-map 22,900 + 3,059 field logs not yet mapped.', daily: [{ day: 'Jun 18', value: 20, target: 1022, unit: 'piles' }, { day: 'Jun 19', value: 79, target: 1022, unit: 'piles' }, { day: 'Jun 22', value: 251, target: 1022, unit: 'piles' }, { day: 'Jun 23', value: 101, target: 1022, unit: 'piles' }, { day: 'Jun 25', value: 370, target: 1022, unit: 'piles' }, { day: 'Jun 26', value: 340, target: 1022, unit: 'piles' }, { day: 'Jun 29', value: 261, target: 1022, unit: 'piles' }, { day: 'Jun 30', value: 234, target: 1022, unit: 'piles' }, { day: 'Jul 1', value: 252, target: 1022, unit: 'piles' }, { day: 'Jul 2', value: 274, target: 1022, unit: 'piles' }, { day: 'Jul 3', value: 134, target: 1022, unit: 'piles' }, { day: 'Jul 6', value: 307, target: 1022, unit: 'piles' }, { day: 'Jul 7', value: 399, target: 1022, unit: 'piles' }, { day: 'Jul 8', value: 646, target: 1022, unit: 'piles' }, { day: 'Jul 9', value: 669, target: 1022, unit: 'piles' }, { day: 'Jul 10', value: 680, target: 1022, unit: 'piles' }, { day: 'Jul 11', value: 680, target: 1022, unit: 'piles' }, { day: 'Jul 13', value: 608, target: 1022, unit: 'piles' }, { day: 'Jul 14', value: 695, target: 1022, unit: 'piles' }, { day: 'Jul 15', value: 481, target: 1022, unit: 'piles' }, { day: 'Jul 16', value: 504, target: 1022, unit: 'piles' }, { day: 'Jul 17', value: 472, target: 1022, unit: 'piles' }, { day: 'Jul 18', value: 608, target: 1022, unit: 'piles' }, { day: 'Jul 20', value: 622, target: 1022, unit: 'piles' }, { day: 'Jul 21', value: 253, target: 1176, unit: 'piles' }, { day: 'Jul 22', value: 202, target: 1419, unit: 'piles' }, { day: 'Jul 23', value: 284, target: 1419, unit: 'piles' }, { day: 'Jul 24', value: 0, target: 1349, unit: 'piles' }] },
      { task: 'Tracker production control (incl. purlin completion)', period: 'Jun 17-Jul 24', minimum: '53 rows/day (required for Aug 30)', above: 4, below: 24, latest: 'Jul 24 (Fri): 30 completed rows (ECCS, E) + Workforce racking installing dampers/actuators on mounted rows. Jul 23: 28 completed (ECCS) + Workforce 17 rows to 50% in EW (~9 row-equiv). 851 done (235 released / 616 pending)', note: 'Purlin installation is integrated into this tracker control metric: a row counts once its purlins are installed. Total done is 851 rows — 235 released by Quality and 616 pending QA approval; the released split is STALE since the Jul 20 C1/C2 release — updated count owed by QA. TWO racking fronts besides ECCS: Workforce racking (2nd crew of the same sub that installs modules) advanced 17 rows to 50% in EW on Jul 23 (~9 row-equivalents) and installed dampers/actuators — the final completion components — on mounted rows Jul 24; those EW rows enter the completed count when they close incl. purlins. United racking crew ramping (~1.5 wks to full rate, Manuel Jul 23). Cumulative under reconciliation — workbook shows 715 pre-assembled / 311 complete.', daily: [{ day: 'Jun 17', value: 15, target: 50, unit: 'units' }, { day: 'Jun 18', value: 35, target: 50, unit: 'units' }, { day: 'Jun 19', value: 26, target: 50, unit: 'units' }, { day: 'Jun 20', value: 31, target: 50, unit: 'units' }, { day: 'Jun 21', value: 0, target: 50, unit: 'units' }, { day: 'Jun 22', value: 48, target: 50, unit: 'units' }, { day: 'Jun 23', value: 31, target: 50, unit: 'units' }, { day: 'Jun 24', value: 0, target: 50, unit: 'units' }, { day: 'Jun 25', value: 57, target: 50, unit: 'units' }, { day: 'Jun 26', value: 26, target: 50, unit: 'units' }, { day: 'Jun 29', value: 29, target: 50, unit: 'units' }, { day: 'Jun 30', value: 30, target: 50, unit: 'units' }, { day: 'Jul 1', value: 51, target: 50, unit: 'units' }, { day: 'Jul 7', value: 29, target: 50, unit: 'units' }, { day: 'Jul 8', value: 0, target: 50, unit: 'units' }, { day: 'Jul 9', value: 0, target: 50, unit: 'units' }, { day: 'Jul 10', value: 0, target: 50, unit: 'units' }, { day: 'Jul 13', value: 29, target: 50, unit: 'units' }, { day: 'Jul 14', value: 49, target: 50, unit: 'units' }, { day: 'Jul 15', value: 35, target: 50, unit: 'units' }, { day: 'Jul 16', value: 35, target: 50, unit: 'units' }, { day: 'Jul 17', value: 25, target: 50, unit: 'units' }, { day: 'Jul 18', value: 0, target: 50, unit: 'units' }, { day: 'Jul 20', value: 21, target: 50, unit: 'units' }, { day: 'Jul 21', value: 25, target: 51, unit: 'units' }, { day: 'Jul 22', value: 39, target: 51, unit: 'units' }, { day: 'Jul 23', value: 28, target: 51, unit: 'units' }, { day: 'Jul 24', value: 30, target: 52, unit: 'units' }] },
      { task: 'Module installation', period: 'Jul 3-Jul 24 field start', minimum: '3,803 modules/day (required for Sep 6)', above: 0, below: 18, latest: 'Jul 24 (Fri): 3,134 modules — Workforce 1,730 + Brumont 1,404 (Zone C)', note: 'Jul 23: 3,456 (Brumont 2,000 + Workforce 1,456); Jul 24: 3,134 (Brumont down 4 people). Record 3,601 on Jul 20; four straight days at 2,887-3,456 but still short of the 3,803/day single goal. (5,531/day is the full-field capacity, not a target.) Released tracker rows remain the watch item — the QA split is stale since Jul 20.', daily: [{ day: 'Jul 3', value: 234, target: 3738, unit: 'modules' }, { day: 'Jul 6', value: 780, target: 3738, unit: 'modules' }, { day: 'Jul 7', value: 156, target: 3738, unit: 'modules' }, { day: 'Jul 8', value: 936, target: 3738, unit: 'modules' }, { day: 'Jul 9', value: 1308, target: 3738, unit: 'modules' }, { day: 'Jul 10', value: 1802, target: 3738, unit: 'modules' }, { day: 'Jul 11', value: 517, target: 3738, unit: 'modules' }, { day: 'Jul 13', value: 2922, target: 3738, unit: 'modules' }, { day: 'Jul 14', value: 2335, target: 3738, unit: 'modules' }, { day: 'Jul 15', value: 780, target: 3738, unit: 'modules' }, { day: 'Jul 16', value: 858, target: 3738, unit: 'modules' }, { day: 'Jul 17', value: 2226, target: 3738, unit: 'modules' }, { day: 'Jul 18', value: 0, target: 3738, unit: 'modules' }, { day: 'Jul 20', value: 3601, target: 3738, unit: 'modules' }, { day: 'Jul 21', value: 3082, target: 3754, unit: 'modules' }, { day: 'Jul 22', value: 2887, target: 3776, unit: 'modules' }, { day: 'Jul 23', value: 3456, target: 3776, unit: 'modules' }, { day: 'Jul 24', value: 3134, target: 3785, unit: 'modules' }] },
      { task: 'ITS MV plowing', period: 'Jun 17-Jul 17', minimum: '1 completed segment/day', above: 11, below: 14, latest: 'Jul 24 export: 0 new segments — 36 of 46 holds; both drills on the DC + MV wetland bores', note: 'Jul 15 ITS tracker: 36 of 46 segments complete (76.6%), 0 in progress. 120,738 ft installed. MV11A 7/10, MV11B 10/12, MV12A 10/13, MV12B 9/11.', daily: [{ day: 'Jun 17', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 18', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 19', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 20', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 21', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 22', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 23', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 24', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 25', value: 3, target: 1, unit: 'seg' }, { day: 'Jun 26', value: 4, target: 1, unit: 'seg' }, { day: 'Jun 27', value: 1, target: 1, unit: 'seg' }, { day: 'Jun 28', value: 0, target: 1, unit: 'seg' }, { day: 'Jun 29', value: 2, target: 1, unit: 'seg' }, { day: 'Jun 30', value: 5, target: 1, unit: 'seg' }, { day: 'Jul 1', value: 0, target: 1, unit: 'seg' }, { day: 'Jul 2', value: 1, target: 1, unit: 'seg' }, { day: 'Jul 6', value: 0, target: 1, unit: 'seg' }, { day: 'Jul 7', value: 0, target: 1, unit: 'seg' }, { day: 'Jul 8', value: 5, target: 1, unit: 'seg' }, { day: 'Jul 9', value: 2, target: 1, unit: 'seg' }, { day: 'Jul 10', value: 5, target: 1, unit: 'seg' }, { day: 'Jul 11', value: 1, target: 1, unit: 'seg' }, { day: 'Jul 13', value: 2, target: 1, unit: 'seg' }, { day: 'Jul 14', value: 2, target: 1, unit: 'seg' }, { day: 'Jul 15', value: 3, target: 1, unit: 'seg' }, { day: 'Jul 16', value: 0, target: 1, unit: 'seg' }, { day: 'Jul 17', value: 0, target: 1, unit: 'seg' }] },
      { task: 'ITS HDD boring', period: 'Jul 2-Jul 20 measured days', minimum: '1 completed bore/day', above: 4, below: 8, latest: 'Jul 24: MV boring 17 of 20 (85%, 5,162 ft); DC bores 2 of 14 complete (391 LF), 1 in progress — two drills running from Jul 24', note: 'Jul 24 ITS control: MV 17 done / 1 in progress / 2 pending (5,162 ft); DC 2 complete Jul 22 (DC15HB-04 210.6 LF + DC12HB-08 180.6 LF). Second, larger drill on site — one rig on DC ducts, one on MV wetland bores.', daily: [{ day: 'Jul 2', value: 1, target: 1, unit: 'bores' }, { day: 'Jul 6', value: 0, target: 1, unit: 'bores' }, { day: 'Jul 7', value: 0, target: 1, unit: 'bores' }, { day: 'Jul 8', value: 1, target: 1, unit: 'bores' }, { day: 'Jul 9', value: 1, target: 1, unit: 'bores' }, { day: 'Jul 10', value: 1, target: 1, unit: 'bores' }, { day: 'Jul 11', value: 1, target: 1, unit: 'bores' }, { day: 'Jul 13', value: 2, target: 1, unit: 'bores' }, { day: 'Jul 14', value: 0, target: 1, unit: 'bores' }, { day: 'Jul 15', value: 0, target: 1, unit: 'bores' }, { day: 'Jul 16', value: 0, target: 1, unit: 'bores' }, { day: 'Jul 17', value: 0, target: 1, unit: 'bores' }, { day: 'Jul 20', value: 1, target: 1, unit: 'bores' }] }
    ],
    successors: [
      { activity: 'Tracker structural assembly', dependency: 'Completed piles by zone/block; final tracker finish after final pile finish', impact: 'Can overlap piling only in released areas. Final tracker structure cannot finish before the revised late-July pile forecast; the August 30 tracker-completion estimate requires 40 completed rows/day.', mitigation: 'Prioritize tracker crews into released workfronts and maintain linked finish-to-finish controls.' },
      { activity: 'Tracker completion incl. purlins', dependency: 'Completed tracker structure; purlins installed concurrently (sufficient units on site)', impact: 'Purlins are not the restriction, and the RED TORQUE TUBE outage is resolved — GameChange delivered ALL 9 tube trucks Fri Jul 24; only 16 purple tubes remain (Wed Jul 29) plus one missing purple bundle claimed on PL-3295-094-HT. Tracker completion is now controlled by assembly crew ramp (United racking ~1.5 wks from full rate) and QA release, best-estimate finish August 30.', mitigation: 'Hold >= 48 tracker units/day, ramp toward 40 completed rows/day, and keep same-week QA turnover of finished rows.' },
      { activity: 'Module installation', dependency: 'Completed tracker rows with both Purlin types installed; final module finish after final purlin finish', impact: 'Module release is controlled by completed, QA-released tracker rows (purlins installed with the trackers). Final module completion is required one week after the August 30 tracker completion — by September 6.', mitigation: 'Mobilize a controlled module crew only against fully released rows and maintain a block-level tracker/purlin/module constraint log.' },
      { activity: 'DC string wiring / combiner work', dependency: 'Modules set and accessible rows', impact: 'Crews trail module installation block-by-block, but the binding constraint is now Chemik LV material: bulk production ~Aug 7, sea 5-6 wks (mid-late Sept) — too late for Sep 25. Only 18% of 3-string harness shipped.', mitigation: 'Air-freight the final Chemik shipments to land before end of August (Luis Romero escalation Jul 17); sequence electrical crews by completed inverter block; use partial completion packages.' },
      { activity: 'Commissioning and MC', dependency: 'Continuous mechanical completion by zone', impact: 'On the re-cascaded dates (trackers Aug 30, modules Sep 6, LV/DC Sep 18) the Sep 25 MC target is achievable with limited float; pre-commissioning Sep 14 - Oct 15 protects the Oct 16 PIS.', mitigation: 'Convert on-site purlin stock into completed tracker rows at >= 48 units/day, hold the Jul 28 pile gate, ramp modules to full-field rate, and prepare weekend/OT acceleration.' }
    ],
    schedule: [
      { activity: 'D&F Pre-Drilling', contractor: 'Kalamazoo Excavating', start: '2026-05-06', end: '2026-06-30', status: 'Complete', progress: 100, baseline: 0, note: 'The June 30 Construction Management PROGRESS sheet shows 7,694 of 7,694 drill-and-backfill units complete.' },
      { activity: 'GameChange material delivery sequence', contractor: 'GameChange / NTG / Landstar', start: '2026-06-17', end: '2026-07-16', status: 'Critical', progress: 90, baseline: 55, note: 'TUBES RESOLVED: GameChange delivered ALL 9 torque-tube trucks Fri Jul 24 (moved up from a Sat/Mon split to avoid weekend offload costs) — after Friday only 16 purple tubes remain to complete the BOM, committed Wed Jul 29. OPEN CLAIM: one purple torque-tube bundle missing from load PL-3295-094-HT (Manuel, Jul 24). Workbook Jul 24: tubes 20,908 of 28,869 delivered (72.4%) — pre-Friday-trucks cut. Prior open items: POD pending on PL-3295-084-HT; GameChange trucks staging on public roads (Road Commission monitoring, fines passed to GameChange). Site pile stock: 28,343 delivered vs 25,959 executed — 2,384-pile buffer. Receiving cap 14 pile + 8 racking loads/day; loads count as scheduled until POD/site receipt.' },
      { activity: 'United Zone F mobilization and pile-spot marking', contractor: 'United', start: '2026-06-15', end: '2026-06-21', status: 'Complete', progress: 100, baseline: 0, note: 'Completed on schedule: marking, mobilization and onboarding closed; United began ramming Jun 22 and has produced daily since.' },
      { activity: 'Overall pile installation acceleration', contractor: 'All pile contractors', start: '2026-06-22', end: '2026-07-28', status: 'Critical', progress: 82.8, baseline: 48.4, note: '5,393 piles remain (official block-map 22,900 + 3,059 field logs not yet mapped): holding July 28 would need ~1,798 piles/day vs ~560 crew capacity — the finish now projects ~Aug 7 (Jose, Jul 22). Jul 23: 284 (United 192 G + 30 F + ECCS 62 E, 4 of 6 United rigs running); Jul 24: NO pile production reported. Rig repairs and the missing daily logs are the escalated levers.' },
      { activity: 'Tracker assembly incl. purlin install', contractor: 'ECCS', start: '2026-06-08', end: '2026-08-30', status: 'At Risk', progress: 34.2, baseline: 0, note: 'Jul 23-24: 28 + 30 rows (ECCS, Zone E) — 851 done / 235 QA-released / 616 pending QA (released split stale since the Jul 20 C1/C2 release). United racking crew ramping (~1.5 wks to full rate); Workforce racking on dampers/actuators Jul 24. Cumulative under reconciliation vs the workbook (715 pre-assembled / 311 complete). QA release cadence is the controlling item for the module front.' },
      { activity: 'ITS HDD boring', contractor: 'ITS', start: '2026-06-12', end: '2026-08-15', status: 'Active', progress: 85, baseline: 0, note: 'Jul 24 ITS control: MV 17 of 20 bores complete (85%, 5,162 ft), 1 in progress, 2 pending; DC cable-duct bores 2 of 14 COMPLETE (391 LF, both Jul 22), DC03HB-02 in progress. Second, larger drill on site — two rigs from Jul 24 (one DC, one MV wetlands). EGLE denied swapping the remaining bores for plowing (Jul 17) — the last continue with ~100 ft extensions each past the wetland.' },
      { activity: 'ITS MV cable plowing', contractor: 'ITS', start: '2026-06-25', end: '2026-08-15', status: 'Active', progress: 76.6, baseline: 0, note: 'Jul 15 ITS tracker: 36 of 46 segments complete (76.6%) — +3 on Jul 15 (MV11A-S01/S02, MV11B-S02); 120,738 ft installed, 11,586 ft plowed on Jul 15.' },
      { activity: 'Control building foundation and delivery gate', contractor: 'AB Power / SET team', start: '2026-06-20', end: '2026-07-10', status: 'Complete', progress: 100, baseline: 0, note: 'GATE MET: control building delivered and set on its foundation the night of July 7, three days ahead of the July 10 required-on-site date.' },
      { activity: 'SET equipment required-on-site gate', contractor: 'SET team / Procurement / Suppliers', start: '2026-06-24', end: '2026-07-10', status: 'Critical', progress: 50, baseline: 0, note: 'MAJOR RECOVERY Jul 24: the MAIN POWER TRANSFORMER arrived and was SET on its foundation (15:33, crane set onto the completed berm/foundation ready since Jul 12) — the largest item of the missed Jul 10 gate is closed 14 days late. BREAKERS are still awaited and several electrical items remain committed after the gate. Control building on site since Jul 7. Jul 24 SET tracker: overall 20.0% (civil 59.3%, structural 11.3%, electrical 5.2%). Jul 17 review: AB Power presented no SET work plan or material-delivery plan — Greensol pulling partial scope to a third party (Michael Power) and self-procuring materials; portico steel arriving Jul 16-17; oil-pit grating (tramex) procured to close the payment milestone.' },
      { activity: 'Substation (SET) construction', contractor: 'AB Power / Michael Power / SET team', start: '2026-06-01', end: '2026-09-25', status: 'Critical', progress: 20.0, baseline: 0, note: 'SUBSTATION PIERS accelerating — 6 of 17 COMPLETE incl. concrete by Jul 24 (2 on Jul 22, 5 by Jul 23, 6 by Jul 24), executed by Dig It (AB Power sub) under Axel Cano (SET Site Manager); plan holds 3-4 piers/day. Jul 24 SET tracker: 20.0% overall (civil 59.3%, structural 11.3%, electrical 5.2%) against a ~44% plan-to-date on the linear baseline to the Sep 25 MC — closing but still the lagging critical path. MILESTONE Jul 24: MAIN POWER TRANSFORMER set on its foundation. Breakers and structural steel remain in fabrication (now the controlling items for energization); AB Power has presented no work or delivery plan and Greensol is pulling partial scope to Michael Power. Inverter steel-pile welding procedure received Jul 21 (Daniel Morilla).' },
      { activity: 'Inverter foundation readiness', contractor: 'EPC / Civil / Electrical', start: '2026-06-20', end: '2026-07-25 provisional', status: 'Critical', progress: 95.7, baseline: 0, note: 'Jul 22 field (Manuel/ECCS): another inverter foundation completed in Zone G — 22 of 23 stations complete (95.7%), only 1 remaining. Welding procedure for the inverter steel-pile foundations received Jul 21 (Daniel Morilla) — qualified welding cleared to proceed. Base-plate welding complete on all 18 stations delivered (Axel, Jul 12). On pace ahead of the end-July arrival of the 23 units.' },
      { activity: 'Inverter Installation', contractor: 'EPC / OEM', start: '2026-07-27', end: '2026-09-15', status: 'Confirmed', progress: 0, baseline: 0, note: '23 x 4.2 MW units. Installation is separated from the SET/control-building scope and depends on completed inverter pile foundations before first delivery.' },
      { activity: 'Workforce module crew mobilization', contractor: 'Workforce', start: '2026-06-29', end: '2026-07-06', status: 'Complete', progress: 100, baseline: 0, note: 'Module crews mobilized and producing (Workforce + Brumont, 38 installers on the Jul 9 board); manning stability is tracked in the risks section.' },
      { activity: 'Final module installation completion', contractor: 'Workforce', start: '2026-07-03', end: '2026-09-06', status: 'Critical', progress: 18.0, baseline: 0, note: 'Modules must finish one week after tracker completion: Aug 30 trackers -> Sep 6 module finish. 30,780 modules executed through Jul 24 (Jul 23: 3,456; Jul 24: 3,134; record 3,601 Jul 20); ~3,803/day now required — four straight days near 3,000+; the gap closes with Brumont re-manning and Saturday work.' },
      { activity: 'DC Wire / LV Installation', contractor: 'East Carolina + Self-Perform', start: '2026-07-07', end: '2026-09-18', status: 'Critical', progress: 0, baseline: 0, note: 'Aerial messenger-wire harness / BLA-style install from tracker rows to junction boxes. Total pull 274,720 lf (0% done). Jul 21: United drove the FIRST LV support piles — 13 combiner-box (CB) + 32 tensioning/messenger-wire (TP) piles in Zone F (tracked separately from the 31,352 tracker piles). NOW MATERIAL-GATED: Chemik LV cable/harness finishes production ~Aug 7; sea transit 5-6 wks lands it mid-late Sept, incompatible with Sep 25 MC. Greening escalating for AIR freight to land material before end of August. Cable-pull kick-off Jul 21 on partial air deliveries.' },
      { activity: 'Electrical Pre-Commissioning', contractor: 'EPC + OEMs', start: '2026-09-14', end: '2026-10-15', status: 'Planned', progress: 0, baseline: 0, note: 'Zonal energization after inverter, MV/HDD, tracker, module, and DC/LV turnover by block. Runs Sep 14 - Oct 15 so all zones are energized ahead of the Oct 16 PIS target.' }
    ],
    fieldResourceSnapshots: [
      { label: 'Jun 17 actual', week: 'W25', people: 136, color: '#b53030', offset: -18 },
      { label: 'Jun 30 official', week: 'W27', people: 148, color: '#2769a8', offset: 18 },
      { label: 'Jul 6 field', week: 'W28', people: 70, color: '#168a5b', offset: 48 },
      { label: 'Jul 7 field', week: 'W28', people: 170, color: '#8a4dbf', offset: 78 },
      { label: 'Jul 9 board', week: 'W28', people: 191, color: '#b96f18', offset: 108 },
      { label: 'Jul 16', week: 'W29', people: 198, color: '#66716d', offset: 138 },
      { label: 'Jul 20 current', week: 'W30', people: 192, color: '#0c5f43', offset: 168 }
    ],
    actualResources: [
      { contractor: 'ECCS', people: 60, label: '60 · tracker installation' },
      { contractor: 'WORKFORCE', people: 34, label: '34 · module installation' },
      { contractor: 'UNITED', people: 24, label: '24 · F Area piling' },
      { contractor: 'BRUMONT', people: 17, label: '17 · module installation' },
      { contractor: 'LATNOVVA', people: 13, label: '13 · B Area piling' },
      { contractor: 'GREENSOL', people: 12, label: '12 · EPC management' },
      { contractor: 'ITS', people: 9, label: '9 · electrical MV/HDD' },
      { contractor: 'GREENSOL CONSTRUCTION', people: 7, label: '7 · site supervision' },
      { contractor: 'TOPLAND', people: 6, label: '6 · civil & roads' },
      { contractor: 'ABPOWER', people: 5, label: '5 · electrical systems' },
      { contractor: 'LOUNSBURY', people: 3, label: '3 · civil earthworks' },
      { contractor: 'ECS', people: 2, label: '2 · environmental support' },
      { contractor: 'DIG IT', people: 0, label: '0 · SET foundations (off site)' },
      { contractor: 'HI-TECH', people: 0, label: '0 · substation & QI (off site)' },
      { contractor: 'HURRICANE', people: 0, label: '0 · fencing (off site)' },
      { contractor: 'SWCA', people: 0, label: '0 · environmental (off site)' },
      { contractor: 'WESTWOOD', people: 0, label: '0 · civil consulting (off site)' }
    ],
    todayFieldSnapshot: {
      date: 'Jul 20, 2026',
      total: 192,
      rows: [
        { contractor: 'ECCS', people: 60, category: 'tracker', note: 'Tracker structural installation + QA — Zones C1/C2 releasing today, the controlling front' },
        { contractor: 'WORKFORCE', people: 34, category: 'module', note: 'Module installation crew, primary — ramped to 34' },
        { contractor: 'UNITED', people: 24, category: 'pile', note: 'Zone F pile driving — 24 crew, 4 of 6 rigs (2 damaged)' },
        { contractor: 'BRUMONT', people: 17, category: 'module', note: 'Module installation crew, secondary' },
        { contractor: 'LATNOVVA', people: 13, category: 'pile', note: 'Zone B pile driving — 2 rigs' },
        { contractor: 'GREENSOL (EPC Team)', people: 12, category: 'epc', note: 'Project management and EPC oversight' },
        { contractor: 'ITS', people: 9, category: 'electrical', note: 'Electrical: MV plowing / HDD — DC cable-duct bores started Jul 23' },
        { contractor: 'GREENSOL CONSTRUCTION', people: 7, category: 'epc', note: 'Self-perform site supervision, QA and rework' },
        { contractor: 'TOPLAND', people: 6, category: 'civil', note: 'Internal roads' },
        { contractor: 'ABPOWER', people: 5, category: 'electrical', note: 'Substation (SET) and inverter-station works' },
        { contractor: 'LOUNSBURY', people: 3, category: 'civil', note: 'Civil earthworks / Area G basins' },
        { contractor: 'ECS', people: 2, category: 'civil', note: 'Environmental controls / sediment basins' },
        { contractor: 'DIG IT', people: 0, category: 'electrical', note: 'No crew on site today' },
        { contractor: 'HI-TECH', people: 0, category: 'electrical', note: 'No crew on site today' },
        { contractor: 'HURRICANE', people: 0, category: 'civil', note: 'No fencing crew on site today' },
        { contractor: 'SWCA', people: 0, category: 'support', note: 'No crew on site today' },
        { contractor: 'WESTWOOD', people: 0, category: 'support', note: 'No crew on site today' },
        { contractor: 'KALAMAZOO', people: 0, category: 'support', note: 'No crew on site today' }
      ]
    },
    equipmentNotes: [
      { contractor: 'GreenSol', equipment: 'Site trucks and laptops for management/QC field use; no heavy equipment assigned.', output: 'Daily site walk, safety audits, and progress verification.' },
      { contractor: 'GreenSol Construction', equipment: 'Hand tools and site vehicles supporting self-perform labor.', output: 'Supporting active workfronts; no heavy equipment assigned.' },
      { contractor: 'ECS', equipment: 'No crew or equipment on site today.', output: 'Not applicable.' },
      { contractor: 'Hurricane', equipment: 'Standard fencing install tools (post drivers, hand tools).', output: 'Fence ~95% complete (Rosario Jul 23): A–F done, Zone G remainder + gates remaining.' },
      { contractor: 'Topland', equipment: 'Grading/road equipment (grader, roller).', output: 'Internal roads scope; Area F access blocked ~10 AM by a concrete pour.' },
      { contractor: 'Lounsbury', equipment: 'Earthwork equipment (excavator, dozer) for cut/fill and basin work.', output: 'Cut/fill 100% complete (Jul 17); Area G basin closeout continuing (basins 83%).' },
      { contractor: 'ECCS', equipment: 'Tracker structural installation crew; equipment count varies by workfront.', output: 'Jul 24 (Fri): 53 people — 30 trackers Zone E. Jul 23: 54 people — 28 trackers + 62 tracker piles Zone E.' },
      { contractor: 'United', equipment: '6 ramming machines on site — 2 damaged (4 running).', output: 'Jul 23 (Thu): 222 tracker piles (192 G + 30 motor F) + 15 electrical CB/TP piles — 27 people; refusal-pile reinstalls + tap-downs. NO log posted Jul 24.' },
      { contractor: 'Latnovva', equipment: '2 ramming machines — 1 running, 1 in repair.', output: 'No daily log since Jul 22 (tension-pile corrections Zone A, 0 new) — chase the Latnovva daily report.' },
      { contractor: 'Workforce', equipment: 'TWO crews: module installation (16) + tracker racking (15).', output: 'Jul 24 (Fri): 1,730 modules Zone C + racking crew installing dampers/actuators on mounted rows. Jul 23: 1,456 modules + 17 tracker rows advanced to 50% in EW (~9 row-equiv).' },
      { contractor: 'Brumont', equipment: 'Module installation tools; 14-person crew (lost 4 Jul 24).', output: 'Jul 24 (Fri): 1,404 modules Zone C — 14 people. Jul 23: 2,000 modules (18 people), on target for the 2nd straight day.' },
      { contractor: 'ITS', equipment: 'TWO HDD drills (2nd larger unit arrived Jul 23) + MV cable-plowing machine.', output: 'Jul 24: 36/46 plow segments (120,738 ft), 17/20 MV bores (5,162 ft), 2/14 DC bores (391 LF); crews 11-12.' },
      { contractor: 'AB Power', equipment: 'SET / electrical installation equipment.', output: 'Supporting control-building and SET electrical scope.' },
      { contractor: 'Dig It', equipment: 'SET pier formwork and foundation equipment (AB Power subcontractor).', output: 'Through Jul 24: 6 of 17 substation piers COMPLETE incl. concrete (5/17 Jul 23, 6/17 Jul 24); plan 3-4 piers/day.' },
      { contractor: 'Hi Tech', equipment: 'Electrical / substation support equipment; Quality Inspector coordination.', output: 'SET / substation grounding and commissioning support scope.' },
      { contractor: 'Westwood', equipment: 'No crew or equipment on site today.', output: 'Not applicable.' },
      { contractor: 'SWCA', equipment: 'No crew or equipment on site today.', output: 'Not applicable.' }
    ],
    resourcePlan: [
      { label: 'Total site resources', actual: 191, target: 105, targetLabel: 'Acceleration peak 95-105', note: 'Includes field labor plus management/QC/HSE; actual is the Jul 13 on-site field snapshot (191) tracking current crew allocation.' },
      { label: 'Tracker / piling crew', actual: 85, target: 85, targetLabel: 'ECCS (50) + United (21) + Latnovva (14)', note: 'Tracker (50) and piling (35) combined: 85 personnel dedicated to structural and piling scope.' },
      { label: 'Module crew Phase 1', actual: 26, committed: 26, target: 22, targetLabel: '22 by Jul 7', note: 'Workforce is producing at 26 with the rolling start; primary module crew on site.' },
      { label: 'Module full-field crew', actual: 41, committed: 41, target: 40, targetLabel: '40 by Jul 13+', note: 'Workforce (26) + Brumont (15) = 41 installers on site — full-field module gate achieved.' },
      { label: 'Electrical & SET crew', actual: 27, committed: 27, target: 25, targetLabel: '25 electrical + SET', note: 'ITS (14) + ABPOWER (5) + DIG IT (4) + HI-TECH (4) = 27 electrical and SET-related personnel.' },
      { label: 'Greensol site team', actual: 20, target: 20, targetLabel: '13 staff + 7 labor', note: 'GREENSOL (13) + GREENSOL CONSTRUCTION (7) = 20 EPC team members on site.' },
      { label: 'Civil & environmental crew', actual: 18, committed: 18, target: 15, targetLabel: '15 civil/environmental', note: 'HURRICANE (3) + TOPLAND (7) + LOUNSBURY (3) + WESTWOOD (1) + ECS (2) + SWCA (2) = 18 civil and environmental support.' }
    ],
    mechanicalManpowerLoad: [
      { week: 'Jun 22', pile: 9, tracker: 16, module: 0, management: 13, total: 38 },
      { week: 'Jun 29', pile: 10, tracker: 28, module: 0, management: 13, total: 51 },
      { week: 'Jul 6', pile: 10, tracker: 35, module: 0, management: 13, total: 58 },
      { week: 'Jul 13', pile: 35, tracker: 50, module: 41, management: 20, total: 146 },
      { week: 'Jul 20', pile: 10, tracker: 50, module: 37, management: 13, total: 110 },
      { week: 'Jul 27', pile: 10, tracker: 42, module: 40, management: 13, total: 105 },
      { week: 'Aug 3', pile: 0, tracker: 42, module: 40, management: 13, total: 95 },
      { week: 'Aug 10', pile: 0, tracker: 42, module: 40, management: 13, total: 95 },
      { week: 'Aug 17', pile: 0, tracker: 42, module: 40, management: 13, total: 95 },
      { week: 'Aug 24', pile: 0, tracker: 42, module: 40, management: 13, total: 95 },
      { week: 'Sep 7', pile: 0, tracker: 42, module: 40, management: 13, total: 95 },
      { week: 'Sep 14', pile: 0, tracker: 42, module: 40, management: 13, total: 95 },
      { week: 'Sep 21', pile: 0, tracker: 0, module: 40, management: 10, total: 50 },
      { week: 'Sep 28', pile: 0, tracker: 0, module: 40, management: 10, total: 50 },
      { week: 'Oct 5', pile: 0, tracker: 0, module: 0, management: 5, total: 5 }
    ],
    mechanicalManpowerMilestones: [
      { week: 'Jun 22', label: 'Acceleration plan starts', color: '#b53030', row: 0 },
      { week: 'Jul 27', label: 'Piles complete · Jul 28', color: '#66716d', row: 1 },
      { week: 'Aug 24', label: 'Trackers incl. purlins · Aug 30', color: '#168a5b', row: 0 },
      { week: 'Sep 7', label: 'Modules · Sep 6', color: '#2769a8', row: 1 }
    ],
    personnelOutlook: [
      { week: 'W22', date: 'May 25', people: 135 },
      { week: 'W23', date: 'Jun 1', people: 281 },
      { week: 'W24', date: 'Jun 8', people: 281 },
      { week: 'W25', date: 'Jun 15', people: 281 },
      { week: 'W26', date: 'Jun 22', people: 229 },
      { week: 'W27', date: 'Jun 29', people: 228 },
      { week: 'W28', date: 'Jul 6', people: 228 },
      { week: 'W29', date: 'Jul 13', people: 228 },
      { week: 'W30', date: 'Jul 20', people: 310 },
      { week: 'W31', date: 'Jul 27', people: 220 },
      { week: 'W32', date: 'Aug 3', people: 255 },
      { week: 'W33', date: 'Aug 10', people: 255 },
      { week: 'W34', date: 'Aug 17', people: 205 },
      { week: 'W35', date: 'Aug 24', people: 205 },
      { week: 'W36', date: 'Aug 31', people: 205 },
      { week: 'W37', date: 'Sep 7', people: 205 },
      { week: 'W38', date: 'Sep 14', people: 205 },
      { week: 'W39', date: 'Sep 21', people: 155 },
      { week: 'W40', date: 'Sep 28', people: 155 },
      { week: 'W41', date: 'Oct 5', people: 130 },
      { week: 'W42', date: 'Oct 12', people: 130 },
      { week: 'W43', date: 'Oct 19', people: 75 },
      { week: 'W44', date: 'Oct 26', people: 75 },
      { week: 'W45', date: 'Nov 2', people: 75 },
      { week: 'W46', date: 'Nov 9', people: 75 },
      { week: 'W47', date: 'Nov 16', people: 0 }
    ],
    milestones: [
      { name: 'Mechanical Completion', target: 'Sep 25, 2026', forecast: 'Sep 20-25, 2026', status: 'High', note: 'Re-cascaded dates (trackers Aug 30, modules Sep 6, LV/DC Sep 18) put MC back on the Sep 25 target — achievable only if the Jul 28 pile gate (~736/day required) holds and the module crew reaches full-field rate.' },
      { name: 'Provisional Interconnection', target: 'Oct 16, 2026', forecast: 'Oct 12-16, 2026', status: 'High', note: 'With MC forecast Sep 20-25 and pre-commissioning complete by Oct 15, the Oct 16 PIS target is feasible without renegotiation — protect the SET/inverter path. Jul 24: main power transformer SET on its foundation — the key PIS equipment item is on site; breakers/structural steel now controlling.' },
      { name: 'Commercial Operation Date', target: 'Nov 9, 2026', forecast: 'Nov 5-9, 2026', status: 'Watch', note: 'The re-cascaded MC/PIS dates restore limited float to COD; feasible if the pile gate and module ramp hold.' },
      { name: 'Substantial Completion', target: 'Nov 30, 2026', forecast: 'Nov 30, 2026', status: 'Watch', note: 'Still achievable if COD is protected and outdoor work closes before weather stop.' }
    ],
    risks: [
      { title: 'Chemik LV cable/harness delivery is the new critical path to energization', level: 'Critical', owner: 'Luis Romero Montero / Clara Lopez / Chemik (Felix A. Perez) / Joshua Spalding', note: 'Jul 17 Chemik thread: bulk LV material finishes production ~Aug 7; sea transit is 5-6 weeks, landing it ~Sep 11-18 — incompatible with the Sep 25 completion commitment. Only 18% of the 3-string harness has shipped by air; the remainder (800+800) is not built until Jul 24 and is insufficient to complete Area A. Air shipments in transit: PL_260706 (ETA Jul 16), PL_260601 and PL_260709 (ETA Jul 23) — none contain harness. Jul 21 packing-list reconciliation (Clara/Chemik): PL_260715 jumper quantities do not match; the 72 DB boxes on PL_260609 shipped without listed brackets (Chemik says integrated in the boxes — confirming); PL_260714 correct. No new shipment-status update from Chemik — chase. Luis Romero (Construction Director) has demanded the final shipments move by AIR so all material lands before end of August; without it the LV pull cannot start in earnest and the required rate jumps to ~12,000-17,000 lf/day over a compressed window. This now gates DC/LV, pre-commissioning and the Oct 16 PIS. PROJECT DECISION (Jul 17): ALL remaining Chemik packages are to be AIR-FREIGHTED — sea transport is off the table as it cannot meet the milestones.' },
      { title: 'H&S — wildfire-smoke air-quality alert LIFTED (Jul 20)', level: 'On Track', owner: 'EHS / H&S Manager / Site Management / Greensol / Luis Romero', note: 'H&S item. RESOLVED: the Michigan EGLE statewide air-quality alert (Canadian/Ontario wildfire smoke, issued Jul 14) expired at the end of Monday Jul 20 and was NOT renewed; site-area AQI is back in the normal Moderate range (Jul 22 forecast). On site the event has eased: the only smoke-related stoppage was ECCS pulled off ~3pm Jul 17 (shortening the tracker/Zone E pile day); no further stoppages since, and Saturday Jul 18 crews (United, Latnovva) worked a normal day. Masks remain available; H&S continues to monitor daily AQI. The Jul 17 stoppage stays documented for a potential force-majeure / time-extension claim (Jul 17 procurement acta).' },
      { title: 'SET scope and deliveries at risk — AB Power has no work plan; scope moving to a third party', level: 'Critical', owner: 'Axel Cano / Audelio Zuniga / AB Power / Michael Power / Procurement', note: 'Jul 17 procurement review: AB Power has presented neither a SET work plan nor a material-delivery plan. Greensol is removing partial scope from AB Power (deduct + fee) and bringing in a third party (Michael Power), plus self-buying the missing material list (BUS-connectors flagged urgent). Portico steel structure arriving Jul 16-17 (next-week arrival not yet confirmed). Oil-pit grating (tramex) is being procured separately to close the SET payment milestone 100% and avoid Heelstone payment objections.' },
      { title: 'SCADA and field instrumentation slipping — recovery plan owed', level: 'Critical', owner: 'SCADA supplier / Clara Lopez / Joshua Spalding', note: 'Jul 17 review: a SCADA delay was reported. The FAT can proceed without the servers in the first week of August, but the field boxes and meteo stations will not ship until the first week of September — a risk to zonal energization and the Oct 16 PIS. A recovery plan has been requested and is still owed; the team intends to hold the FAT and press for firm dates.' },
      { title: 'Tracker and pile scope adjustments from the Jul 17 review', level: 'Watch', owner: 'Luis Romero / Audelio Zuniga / Workforce / United', note: 'The remaining 10 MW of tracker assembly is being PULLED from Workforce (capability concern) — reassignment pending (United now holds full mechanical in Zones F & G). Missing piles: Plan B is to double smaller-section site piles or reinforce with concrete while Axel chases supply. EGLE will not allow swapping the remaining HDD bores for plowing; the last 4 bores continue with ~100 ft extensions each past the wetland.' },
      { title: 'Pile production is sliding — rigs down, Latnovva silent, and Jul 24 logged ZERO piles', level: 'Critical', owner: 'United / LATNOVVA / Audelio Zuniga / Manuel Ramirez', note: 'Pile stock is comfortable — 28,343 delivered vs 25,959 executed, a 2,384-unit buffer. The constraint is mechanical and reporting: United ran 4 of 6 rigs Jul 23 (2 damaged) for 222 piles, Latnovva has not reported production since Jul 22, and NO pile log was posted for Jul 24. Jose (Jul 22): "We are drastically reducing pile production — we are now heading to Aug 7. Make the effort to hit the piling completion milestone." Holding Jul 28 would need ~1,798/day vs ~560 capacity; the working projection is ~Aug 7. Rig repairs, the Latnovva/United daily logs, and Saturday work are the recovery levers.' },
      { title: 'Trackers remain the controlling front: 28-30 rows/day vs 53 required', level: 'Critical', owner: 'ECCS / Daniel Morilla / Manuel Ramirez / United / Workforce', note: 'ECCS logged 28 + 30 completed rows Jul 23-24 (Zone E) — the best back-to-back days since Jul 14, but barely half the 53/day required for Aug 30. The SECOND Workforce crew (racking) is also producing trackers — 17 EW rows to 50% Jul 23, dampers/actuators Jul 24 — reported on the scoreboard and credited to the cumulative as the rows close. 851 done / 235 released / 616 pending — the released split is STALE since the Jul 20 C1/C2 release; an updated QA count is owed. Manuel (Jul 23): United is now receiving racking people — expect a step-up in ~1.5 weeks; Workforce racking ran 17 rows at 50% (EW) Jul 23 and dampers/actuators Jul 24; Jose pressed the team Jul 23 to repeat the mechanical recovery on the electrical side. Torque tubes are no longer the constraint (all 9 trucks landed Jul 24). Field cumulative under reconciliation vs the workbook (715 pre-assembled / 311 complete).' },
      { title: 'QA release backlog now binds the module front — and Area F was released without sub documents', level: 'Critical', owner: 'Daniel Morilla (QA/QC) / ECCS / Manuel Ramirez', note: '616 completed tracker rows await Quality approval on top of the 235 released (split stale since Jul 20), after a freeze Jul 10-18 (rows driven but not levelled/aligned). Daniel confirmed Monday Jul 20 that Zones C1 and C2 release today with the Client — the first releases since Jul 10; crews stay concentrated on tracker QA to clear the A6/A7 backlog and Area F progress. Open item flagged by QA: some Area F zones were released internally without the subcontractor submitting quality documents — those documents must be recovered. The released buffer ahead of modules is only ~1.3 days, so released rows are the binding constraint.' },
      { title: 'SET foundation, delivery dates, and equipment commitments all need closure', level: 'Critical', owner: 'Axel Cano / AB Power / Karina Mucino / Joshua Spalding / Project Management', note: 'Jul 24 SET tracker shows 20.0% overall progress (civil 59.3%, structural 11.3%, electrical 5.2%), up from 16.7% on Jul 21 — piers 6 of 17 complete incl. concrete. MILESTONE Jul 24, 15:33: the MAIN POWER TRANSFORMER was delivered and SET on its foundation (containment berm ready since Jul 12) — the biggest energization item is on site, 14 days after the missed Jul 10 gate. BREAKERS are still awaited, structural steel remains in fabrication, and several electrical items show committed dates after the gate — these are now the controlling SET equipment items.' },
      { title: 'ITS is ahead of the electrical sequence — two drills now running', level: 'On Track', owner: 'ITS / Audelio Zuniga / Angel Urbina', note: 'Jul 24 ITS tracker: 36 of 46 plow segments complete (120,738 ft), 17 of 20 MV bores closed (5,162 ft) and 2 of 14 DC cable-duct bores complete (391 LF, both Jul 22; DC03HB-02 in progress). A second, larger drill arrived Jul 23 — from Jul 24 one rig runs the DC ducts and the other the MV wetland bores (Axel). Only 3 MV bores and 10 segments remain; the LV kick-off should confirm crews and work plan for the follow-on scope.' },
      { title: 'Area G civil release must convert into workfront access', level: 'Critical', owner: 'Rosario Ruiz / Audelio Zuniga / Lounsbury', note: 'Rosario Ruiz Week 26 email says Area G is released for pile driving and material distribution. Civil cut/fill in Area G starts after basin completion; this needs to convert quickly into mechanical access.' }
    ]
  };

// ---- Jul 13 field-snapshot render patch (runs after main dashboard script) ----
(function () {
  function patchFieldResources() {
    try {
      var d = window.MURCH_DATA;
      if (!d || !d.todayFieldSnapshot) return;

      var section = document.getElementById('field-resources');
      if (section) {
        var headings = section.querySelectorAll('.section-heading.compact');
        if (headings[1]) {
          var eyebrow = headings[1].querySelector('.eyebrow');
          var h2 = headings[1].querySelector('h2');
          if (eyebrow) eyebrow.textContent = 'Field snapshot | On-site headcount board, ' + d.todayFieldSnapshot.date;
          if (h2) h2.textContent = 'Subcontractor and GreenSol team resources reported on site';
        }
        var ctxP = section.querySelectorAll('.chart-context')[1];
        if (ctxP) ctxP.textContent = 'Total headcount by crew from today’s on-site tracking board. GreenSol management and self-perform labor are combined into a single EPC-team bar; subcontractor crews are shown individually, largest to smallest. Scope breakdown: Trackers & Piling (97), Module Installation (51), Electrical & SET (14), Civil & Fencing (11), GreenSol EPC (19).';
      }

      var resourceTable = document.querySelector('.resource-table table');
      if (resourceTable && d.equipmentNotes) {
        var thead = resourceTable.querySelector('thead');
        var tbody = resourceTable.querySelector('tbody');
        if (thead) thead.innerHTML = '<tr><th>Company</th><th>Machines / equipment</th><th>Latest reported output</th></tr>';
        if (tbody) tbody.innerHTML = d.equipmentNotes.map(function (row) {
          return '<tr><td data-label="Company"><strong>' + row.contractor + '</strong></td>' +
            '<td data-label="Machines / equipment">' + row.equipment + '</td>' +
            '<td data-label="Latest reported output">' + row.output + '</td></tr>';
        }).join('');
      }

      var canvas = document.getElementById('resourceChart');
      if (!canvas) return;
      var snapshot = d.todayFieldSnapshot;
      var rows = snapshot.rows.slice().sort(function (a, b) { return b.people - a.people; });
      var catColors = { epc: '#0c5f43', tracker: '#0a3d2a', pile: '#2769a8', module: '#168a5b', electrical: '#8a4dbf', civil: '#b96f18', set: '#b53030', support: '#9aa39d' };
      var catLabels = { epc: 'GreenSol EPC team', tracker: 'Tracker installation', pile: 'Pile driving', module: 'Module installation', electrical: 'Electrical / SET', civil: 'Civil / fencing', set: 'Substation', support: 'Support / no crew' };
      var rowH = 30;
      var pad = { left: 190, top: 64, right: 70, bottom: 40 };
      var width = 1120;
      canvas.width = width;
      canvas.height = pad.top + rows.length * rowH + pad.bottom;
      canvas.style.height = 'auto';
      var ctx = canvas.getContext('2d');
      var chartW = width - pad.left - pad.right;
      ctx.clearRect(0, 0, width, canvas.height);
      ctx.fillStyle = '#ffffff';
      ctx.fillRect(0, 0, width, canvas.height);
      ctx.textAlign = 'left';
      ctx.fillStyle = '#18201f';
      ctx.font = '800 17px system-ui';
      ctx.fillText(snapshot.total + ' people on site — ' + snapshot.date, 4, 24);
      ctx.font = '700 12.5px system-ui';
      ctx.fillStyle = '#66716d';
      ctx.fillText('GreenSol EPC team + subcontractor crews, sorted by headcount', 4, 44);
      var max = 1;
      rows.forEach(function (r) { if (r.people > max) max = r.people; });
      var barMaxW = chartW - 46;
      rows.forEach(function (row, index) {
        var y = pad.top + index * rowH;
        var barW = row.people > 0 ? Math.max(3, (row.people / max) * barMaxW) : 0;
        ctx.textAlign = 'right';
        ctx.font = '750 13px system-ui';
        ctx.fillStyle = '#18201f';
        ctx.fillText(row.contractor, pad.left - 14, y + rowH / 2 + 4);
        ctx.fillStyle = '#eef2ef';
        ctx.fillRect(pad.left, y + 5, barMaxW, rowH - 12);
        ctx.fillStyle = row.people > 0 ? (catColors[row.category] || '#66716d') : '#c7cdc9';
        if (barW > 0) ctx.fillRect(pad.left, y + 5, barW, rowH - 12);
        ctx.textAlign = 'left';
        ctx.font = '800 13px system-ui';
        ctx.fillStyle = '#18201f';
        ctx.fillText(String(row.people), pad.left + Math.max(barW, 3) + 8, y + rowH / 2 + 4);
      });
      var legendCats = ['epc', 'tracker', 'pile', 'module', 'electrical', 'civil', 'set', 'support'];
      var legendY = canvas.height - 12;
      var legendX = pad.left;
      ctx.font = '700 11px system-ui';
      legendCats.forEach(function (cat) {
        var text = catLabels[cat];
        var textW = ctx.measureText(text).width;
        if (legendX + 24 + textW > width - pad.right) { legendX = pad.left; legendY += 16; }
        ctx.fillStyle = catColors[cat];
        ctx.fillRect(legendX, legendY - 9, 10, 10);
        ctx.fillStyle = '#66716d';
        ctx.textAlign = 'left';
        ctx.fillText(text, legendX + 14, legendY);
        legendX += 18 + textW + 14;
      });
    } catch (e) { /* non-fatal: keep default rendering */ }
  }
  if (document.readyState === 'complete') {
    patchFieldResources();
  } else {
    window.addEventListener('load', patchFieldResources);
  }
  window.addEventListener('resize', function () { window.setTimeout(patchFieldResources, 50); });
}());
